Adding variable soil thickness to CTC
E3SM-Project/E3SM pull request #3609
Opened 2020-05-28 16:31 UTC by mabrunke

Adds consistency to run variable soil thickness with CTC, fixes a few remaining bugs in variable soil thickness.  The code is ready to be reviewed, but tests with variable soil and CTC turned on need to be added.  Also, aveDTB needs to be added to surfdata by Teklu Tesfa so that the variable soil tests actually use the variable soil thickness.

2020-05-28 22:01 UTC, rljacob commented
is this for v2?

2020-05-28 23:17 UTC, mabrunke commented
@rljacob I'm hoping that it can be if Teklu's changes to mksurfdata are merged so that the depths-to-bedrock needed to do this can be added to surfdata.

2020-07-30 17:43 UTC, rljacob commented
@mabrunke what is the status of this PR?  Is it still "do not merge"?

2020-07-30 19:41 UTC, mabrunke commented
@rljacob it is my understanding that a PR can't be made ready for merging until the design document is completed, and I'm wrapping up the final component, the validation, right now.  Also, I need to merge Teklu's branch (tktesfa2014/lnd/archv2_variable_SDepth) to add grid cell mean depth-to-bedrock into the surfdata.

2020-07-30 22:37 UTC, rljacob commented
You are correct.  Thanks for the update.

2020-08-24 02:55 UTC, rljacob commented
@tktesfa2014 if you want to merge your branch to this branch, don't use a PR for that.  Just do the merge and push the new version of the mabrunke/lnd/varsoil-in-ZD2009-with-BGC branch to github.

2020-08-24 16:38 UTC, mabrunke commented
@rljacob would you rather have them merged?  I think @tktesfa2014 is worried that he won't get credit for his JIRA task on his branch if the two branches are merged.  Also, there will be conflicts, because my branch is derived from an older version of master than his.

2020-08-24 16:46 UTC, rljacob commented
Yes that's also fine.

2020-08-24 16:54 UTC, mabrunke commented
@rljacob can I open this up for review then?

2020-08-24 18:15 UTC, rljacob commented
yes

2020-09-03 17:32 UTC, rljacob commented
@mabrunke do you want other reviewers besides @bishtgautam ?

2020-09-03 18:12 UTC, mabrunke commented
@rljacob that's who I've relied on in the past for variable soil without BGC.  Do you have any other suggestions?

2020-09-03 21:58 UTC, bishtgautam requested changes
@mabrunke Few minor changes are requested.

2020-09-03 21:58 UTC, bishtgautam commented on components/clm/src/main/controlMod.F90
> +             use_var_soil_thick = .false.
Instead of modifying `use_var_soil_thick`, throw in an error.

2020-09-03 21:58 UTC, bishtgautam commented on components/clm/src/biogeochem/NitrogenDynamicsMod.F90
> +	 nlevbed = nlev2bed(c)
Please indent this line

2020-09-03 21:58 UTC, bishtgautam commented on components/clm/src/biogeochem/NitrogenDynamicsMod.F90
> +	 nlevbed = nlev2bed(c)
Please indent this line

2020-09-03 21:58 UTC, bishtgautam commented on components/clm/src/biogeochem/NitrogenDynamicsMod.F90
> +                  r_fix = -6.25_r8*(exp(-3.62_r8 + 0.27_r8*(t_soi10cm_col(c)-273.15_r8)*(1.0_r8-0.5_r8*(t_soi10cm_col(c)-273.15_r8)/25.15_r8))-2.0_r8)
It seems to be that `&` is removed to make a single very long line. If that is correct, please revert the change.

2020-09-03 21:58 UTC, bishtgautam commented on components/clm/src/biogeochem/PhosphorusDynamicsMod.F90
> +	 nlevbed = nlev2bed(c)
Please indent this line

2020-09-03 21:58 UTC, bishtgautam commented on components/clm/src/biogeochem/PhosphorusDynamicsMod.F90
> +	 nlevbed = nlev2bed(c)
Please indent this line

2020-09-07 16:56 UTC, mabrunke commented
@bishtgautam I've made the changes you requested.

2020-09-08 23:51 UTC, bishtgautam approved these changes

2020-09-10 22:34 UTC, bishtgautam commented
@mabrunke I created a new branch of the latest master and cherry-picked your commits. I modified the commit that added the new test to avoid conflict. My new branch is `bishtgautam/lnd/mabrunke-varsoil-in-ZD2009-with-BGC`. I don't expect there would be any difference between my branch and your branch since there were no conflicts during cherry-picking. Could you test out my branch to make sure I have not broken your new physics? If everything works, I will update this PR.

2020-09-18 00:29 UTC, mabrunke commented
@bishtgautam your branch looks like it incorporated all of the changes to ELM that I've made, but I'm trying to diagnose why NaNs are produced sometimes for TWS in urban columns.  Right now, I'm at a loss, because it doesn't look like any contributions to this are NaNs.

2020-09-18 00:48 UTC, bishtgautam commented
Do you get NaNs with your branch?

2020-09-18 01:06 UTC, mabrunke commented
Yes, I was getting NaNs in my branch too, but only when variable soil thickness is turned on.

2020-10-13 16:23 UTC, mabrunke commented
@bishtgautam I've been working with Yilin Wang on rectifying the NaNs, and we found a remaining bug in SoilHydrologyMod.F90.  I've pushed a commit to your branch that rectifies this.

2020-10-17 15:23 UTC, bishtgautam commented
@mabrunke I don't see a new commit in this PR. Did you forget to push the new commit to GitHub?

2020-10-22 21:02 UTC, mabrunke commented
@bishtgautam, I thought I did.  Maybe GitHub won't let me, because I'm not the owner of the branch.  I also see that @pnlfang may have a correction to this same problem (and another one) that is under review.

2020-10-22 21:19 UTC, rljacob commented
@mabrunke what was the error message?  You are in the "developers" group so you can push to any branch except master/next.

2020-10-22 21:43 UTC, mabrunke commented
@rljacob I didn't get an error message.  It seemed like it worked.

2020-10-22 21:46 UTC, mabrunke commented
@bishtgautam the commit is there c2c4032 in your branch bishtgautam/lnd/mabrunke-varsoil-in-ZD2009-with-BGC.

2020-10-22 22:25 UTC, rljacob commented
@bishtgautam please close this PR and open a new one with the corrected branch.

2020-10-30 13:56 UTC, bishtgautam commented
Replaced by #3921

2020-10-30 13:56 UTC, closed without merging