Mods for energy diagnostics
E3SM-Project/E3SM pull request #3686
Opened 2020-07-07 21:16 UTC by oksanaguba

2020-07-09 17:39 UTC, rljacob commented
@oksanaguba can you please clean up this branch and combine commits that just say "cleanup"?

2020-07-09 18:42 UTC, oksanaguba commented
@rljacob how would you want me to do that? squash them? To clarify, there is a reason for many clean up commits -- I ran a bfb  test between each of them. To save my work in between, I used git commit instead of some other mechanism..

2020-07-09 18:49 UTC, rljacob commented
Yes squash them.  That's a perfectly fine dev practice but when it comes time to merge to master, we only want substantive commit messages in the history.

2020-07-28 21:49 UTC, AaronDonahue commented
@oksanaguba , I'm just now checking back on this PR.  Have you had a chance to squash the commit history and write up a description of the PR?

2020-08-14 03:59 UTC, rljacob commented
@oksanaguba please fix this PR.  Squash commits, write a description.

2020-08-14 20:17 UTC, oksanaguba commented
@rljacob i tried to squash but i keep getting an error. there is a commit, master merge into this branch, that rebase cannot apply.

2020-08-14 20:17 UTC, oksanaguba commented
@AaronDonahue sorry i missed your message, i will try to finalize this PR.

2020-08-18 21:59 UTC, oksanaguba commented
@mt5555 if you could please review changes in prim_state for energy output?

2020-09-03 17:34 UTC, rljacob commented
@mt5555 please review this.

2020-09-03 19:55 UTC, mt5555 commented
This code is adding advanced energy budget diagnostics to the physics - I'm not familiar enough with that code to be a reviewer. Suggest @singhbalwinder

2020-09-03 20:11 UTC, oksanaguba commented
@mt5555 could you please look at homme files only?

2020-09-03 20:36 UTC, mt5555 approved these changes

2020-09-03 20:36 UTC, mt5555 commented on components/homme/src/share/control_mod.F90
> +#ifdef MODEL_THETA_L
cound this code be moved into the model specific model_init_mod.F90?  that would let us get rid of the #ifdef MODEL_THETA_L stuff.  (I'm always trying to reduce #ifdef's )

2020-09-22 22:02 UTC, AaronDonahue commented
@oksanaguba and @mt5555 , are we okay to start merging this without the review from @singhbalwinder?

2020-09-22 22:03 UTC, oksanaguba commented
@AaronDonahue No, please, let him look. I want to do another check in this PR but I was waiting to see what the reviewers say.

2020-09-22 22:08 UTC, AaronDonahue commented
@oksanaguba , great, I think he was pinged with my comment so I'll wait for his review to come in.  Thanks for responding.

2020-09-22 22:59 UTC, singhbalwinder commented
I am so sorry about the delay. I started looking at it and will finish the review soon.

2020-09-23 12:25 UTC, singhbalwinder requested changes
Thanks @oksanaguba for adding this feature. I left some comments based on my understanding of the code. Please feel free to push back if you think my suggested changes may cause other issues.

2020-09-23 12:25 UTC, singhbalwinder commented on components/cam/src/physics/cam/check_energy.F90
> +          se(i) = se(i) + t(i,k)*cpair*pdel(i,k)/gravit
I may be wrong but from my reading of the code, it looks like cpairv_loc can be different from cpair for WACCM simulations. I haven't run the code in WACM mode to verify that.

2020-09-23 12:25 UTC, singhbalwinder commented on components/cam/src/physics/cam/check_energy.F90
> +    call energy_helper_eam_def(state%u,state%v,state%T,state%q,state%ps,state%pdel,state%phis, &
Thanks for encapsulating this repeated code in a subroutine!

2020-09-23 12:25 UTC, singhbalwinder commented on components/cam/src/physics/cam/physics_types.F90
> +    real(r8) :: rairv_loc(state%psetcols,pver)  ! Local zvir array pointer
I also like removing runtime allocations-deallocations if not absolutely needed. These are expensive calls and sometime defragments the memory.

2020-09-23 12:25 UTC, singhbalwinder commented on components/cam/src/physics/cam/physics_types.F90
> +    zvirv(:,:) = zvir
Are we getting rid of WACCM related codes? I am not familiar with WACCM, so I am not sue how WACCM simulations will be impacted by this change.

2020-10-08 01:54 UTC, rljacob commented
@oksanaguba please respond to @singhbalwinder 's review comments.

2020-10-08 04:45 UTC, oksanaguba commented
I cannot work on this for another few weeks, closing for now.

2020-10-08 04:45 UTC, closed without merging

2021-07-28 22:54 UTC, oksanaguba commented
@wlin7 -- I would like to ask you about this PR. I want to revive a part of it which removes cpair arrays (not used since we have const pair for now) and repeated energy calculations, so that energy definition is in one routine only. cpairv, rairv (zvirv) arrays are used in WACCM, but is anyone actually using this in e3sm? Besides asking you, I will ask Yaga R. and Jack in case they use WACCM options.