Combined plant hydraulics and variable soil thickness.
E3SM-Project/E3SM pull request #3898
Opened 2020-10-21 01:58 UTC by pnlfang

This change will allow simulations with both plant hydraulics and variable soil thickness options on.  Minor bug fix for NaNs of TWS and wetland energy balance issue when only variable soil thickness is active.

2020-10-21 03:31 UTC, rljacob commented
@pnlfang is the BFB for v2 watercycle cases?

2020-10-21 03:31 UTC, rljacob commented
Is this needed for any v2 sims?

2020-10-21 03:32 UTC, rljacob commented
@pnlfang please point to the issue describing the bug this PR fixes.  Or create one if necessary.

2020-10-21 16:59 UTC, pnlfang commented
@rljacob BFB is for water cycle cases. It's not needed for v2 sims. As for the bug fix: 
1. There is energy balance error for wetlands caused by inconsistent bedrock heat capacity. See https://github.com/E3SM-Project/E3SM/blob/934a7e6585457a22779130e5f090dce140311798/components/elm/src/biogeophys/SoilStateType.F90#L572 and https://github.com/E3SM-Project/E3SM/blob/934a7e6585457a22779130e5f090dce140311798/components/elm/src/biogeophys/SoilTemperatureMod.F90#L1034
2. The code gave total water storage NaNs error because these two lines (https://github.com/E3SM-Project/E3SM/blob/fcaeac651209f1510c6d44d4c64a4bbe9666e79a/components/elm/src/biogeophys/SoilHydrologyMod.F90#L1106, https://github.com/E3SM-Project/E3SM/blob/fcaeac651209f1510c6d44d4c64a4bbe9666e79a/components/elm/src/biogeophys/SoilHydrologyMod.F90#L1189 ) didn't account for variable soil thickness.

2020-10-22 05:28 UTC, bishtgautam commented
@pnlfang You need to create a new issue under https://github.com/E3SM-Project/E3SM/issues and then add "Fixes #<new-issue>" in the first comment of this PR. Here is an example: #3875 was an issue that was closed by PR #3874. See the first comment in PR #3874.

2020-10-22 05:30 UTC, bishtgautam requested changes
Remove the commented code in various files

2020-10-22 05:30 UTC, bishtgautam commented on components/elm/src/biogeophys/PhotosynthesisMod.F90
> +         do j = 1,nlevbed
Remove the commented code

2020-10-22 05:30 UTC, bishtgautam commented on components/elm/src/biogeophys/PhotosynthesisMod.F90
> +!         nlevbed = nlev2bed(c)
Remove the commented code

2020-10-22 05:30 UTC, bishtgautam commented on components/elm/src/biogeophys/PhotosynthesisMod.F90
> +!         nlevbed = nlev2bed(c)
Remove the commented code

2020-10-22 05:30 UTC, bishtgautam commented on components/elm/src/biogeophys/PhotosynthesisMod.F90
> +!         nlevbed = nlev2bed(c)
Remove the commented code

2020-10-22 17:25 UTC, pnlfang commented on components/elm/src/biogeophys/PhotosynthesisMod.F90
> +!         nlevbed = nlev2bed(c)
Removed.

2020-11-16 18:27 UTC, pnlfang commented
Fixes https://github.com/E3SM-Project/E3SM/issues/3944.

2020-12-17 18:26 UTC, rljacob commented
Notes from IG telecon:  may need rebase.  Ready.

2021-01-06 15:29 UTC, bishtgautam approved these changes

2021-01-21 18:38 UTC, rljacob commented
@pnlfang you need to figure out why this was non-BFB when tested.

2021-05-20 13:36 UTC, bishtgautam commented
Closing this as PR as no work has been done on it to fix it.

2021-05-20 13:36 UTC, closed without merging