Adds ocean semi-implicit barotropic mode solver
E3SM-Project/E3SM pull request #3977
Opened 2020-12-08 15:02 UTC by mark-petersen

This adds a semi-implicit barotropic solver for ocean time-stepping. Current default is split explicit, and this new option is default off. 

See https://github.com/MPAS-Dev/MPAS-Model/pull/422

[BFB]

2020-12-08 15:11 UTC, mark-petersen commented
MPAS code changes currently show #3937.  Those will go after #3937 is merged.

Tested with the standard `config_time_integrator = 'split_explicit'`
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ld5_P512.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
Also tested with `config_time_integrator = 'semi-implicit'`. It requires LAPACK, which is available on most machines. 

<details>
<summary> For now, we are testing on cori by adding: </summary> <p>


```
diff --git a/cime_config/machines/config_machines.xml b/cime_config/machines/config_machines.xml
index 70e1170cd..843bbf8b7 100644
--- a/cime_config/machines/config_machines.xml
+++ b/cime_config/machines/config_machines.xml
@@ -143,6 +143,7 @@
         <command name="load">PrgEnv-intel/6.0.5</command>
         <command name="rm">intel</command>
         <command name="load">intel/19.0.3.199</command>
+        <command name="load">/global/homes/m/mturner/.local/modulefiles/lapack/3.9.0/intel19</command>
       </modules>

       <modules compiler="gnu">
@@ -151,6 +152,7 @@
         <command name="load">gcc/8.3.0</command>
         <command name="rm">cray-libsci</command>
         <command name="load">cray-libsci/19.06.1</command>
+        <command name="load">/global/homes/m/mturner/.local/modulefiles/lapack/3.9.0/gnu8.3.0</command>
       </modules>

       <modules>
@@ -295,6 +297,7 @@
         <command name="load">PrgEnv-intel/6.0.5</command>
         <command name="rm">intel</command>
         <command name="load">intel/19.0.3.199</command>
+        <command name="load">/global/homes/m/mturner/.local/modulefiles/lapack/3.9.0/intel19</command>
       </modules>

       <modules compiler="gnu">
@@ -303,6 +306,7 @@
         <command name="load">gcc/8.3.0</command>
         <command name="rm">cray-libsci</command>
         <command name="load">cray-libsci/19.06.1</command>
+        <command name="load">/global/homes/m/mturner/.local/modulefiles/lapack/3.9.0/gnu8.3.0</command>
       </modules>

       <modules>
diff --git a/components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml b/components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
index 2669b370a..2e42275bf 100644
--- a/components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
+++ b/components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
@@ -48,7 +48,7 @@
 <config_dt ocn_grid="oARRM60to6">'00:05:00'</config_dt>
 <config_dt ocn_grid="EC30to60E2r2">'00:30:00'</config_dt>
 <config_dt ocn_grid="WC14to60E2r3">'00:10:00'</config_dt>
-<config_time_integrator>'split_explicit'</config_time_integrator>
+<config_time_integrator>'semi_implicit'</config_time_integrator>

 <!-- hmix -->
 <config_hmix_scaleWithMesh ocn_grid="oQU480">.false.</config_hmix_scaleWithMesh>
```
</details>

Then with semi-implicit it passes:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
```

2020-12-08 16:51 UTC, mattdturner commented
I have run a suite of tests for the SI code for both `config_btr_si_partition_match_mode` equals `.false.` and `.true.`. The results are

**config_btr_si_partition_match_mode = .false.**
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln9_P8192.T62_oRRS18to6v3.GMPAS-IAF.cori-knl_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu

--
FAIL:
FAIL PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu COMPARE_base_single_thread
FAIL PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel COMPARE_base_modpes
FAIL PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu COMPARE_base_modpes
FAIL PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel COMPARE_base_single_thread
FAIL PET_Ln9_P8192.T62_oRRS18to6v3.GMPAS-IAF.cori-knl_gnu COMPARE_base_single_thread
FAIL PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-haswell_gnu COMPARE_base_modpes
FAIL PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel COMPARE_base_single_thread
FAIL PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-haswell_intel COMPARE_base_modpes
FAIL PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu COMPARE_base_single_thread
```

**config_btr_si_partition_match_mode = .true.**
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PET_Ln9_P8192.T62_oRRS18to6v3.GMPAS-IAF.cori-knl_gnu
PET_Ln9_P8192.T62_oRRS18to6v3.GMPAS-IAF.cori-knl_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
SMS_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu

--
FAIL:
FAIL PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu COMPARE_base_single_thread
FAIL PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-haswell_gnu COMPARE_base_modpes
FAIL PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu COMPARE_base_single_thread
FAIL PET_Ln3_D.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel COMPARE_base_single_thread
FAIL PEM_Ln9_D.T62_oQU240.GMPAS-IAF.cori-haswell_intel COMPARE_base_modpes
```

@hyungyukang is looking into the few `PEM_*` tests that are failing, while I am looking at the few `PET_*` tests that are failing.

All tests that I have run (the same list as above) w/ the SI code included in MPAS-O, but using the `split_explicit` timestepping scheme (the current default) have PASSed.  So this PR should not effect any of the tests / model results until the timestepping scheme is changed to `semi-implicit`.

2020-12-16 18:05 UTC, mark-petersen commented
Current HEAD passes MPAS-O nightly regression suite with gnu 6 debug on grizzly. Fails partition by default, but passes with `config_btr_si_partition_match_mode = .true.`.

2020-12-16 19:43 UTC, mattdturner commented
Tested the current HEAD:
PASS:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
```

FAIL:
```
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
```

The FAILs are expected (see Issue https://github.com/E3SM-Project/E3SM/issues/3989), and should be unrelated to this PR.

I also ran a BFB check (`SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi`).  It PASSes the BFB check, but FAILs the `NLCOMP` (expected, since this PR has namelist modifications).

2020-12-16 19:43 UTC, mattdturner approved these changes

2021-01-13 18:36 UTC, mark-petersen commented
Rebased. Testing now.

2021-01-13 18:47 UTC, jonbob requested changes
The changes to the E3SM bld scripts should be made with the automated scripts and not by hand

2021-01-13 18:54 UTC, mattdturner commented
@jonbob I'm not familiar with the automated scripts.  Which files (or subdirectories) should I be making changes to?

2021-01-13 19:07 UTC, jonbob commented
@mattdturner - there are scripts you can run that take the changes in the Registry and make corresponding updates to the E3SM bld scripts. I generally do that, but I can point you at a confluence page

2021-01-13 19:44 UTC, mark-petersen commented
Passes (with split explicit timestepping, not new semi-implicit)
```
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
SMS_D.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_gnu
PEM_Ln9_P1024.ne30_oECv3_ICG.A_WCYCL1850S.cori-haswell_gnu
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PET_Ln9.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu
```
That was just a sanity test for testing on next - see above for tests with semi-implicit on. 

Also passes mpas-o nightly regression suite with gnu debug and both split explicit and semi-implicit.

2021-01-13 20:20 UTC, mattdturner commented
On Compy, this passes:
```
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
  - FAIL SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi NLCOMP
  - PASS SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi BASELINE /compyfs/e3sm_baselines/pgi/master:

PEM_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
PET_Ln9.T62_oQU240.GMPAS-IAF.compy_pgi
```
The `NLCOMP` failure is expected.

@jonbob I'll update the namelist files using the automated scripts once you direct me to the Confluence page, but aside from that the PR should be ready to go

2021-01-13 21:07 UTC, vanroekel approved these changes
I'm approving conditionally based on extensive testing, but contingent upon approval from @jonbob

2021-01-13 23:23 UTC, jonbob commented
@mattdturner - it's on this page, but not as straightforward as it sounds in mpas-o due to some unnecessary things included in the Registry:

[Updating+MPAS+Framework+and+Components+in+ACME](https://acme-climate.atlassian.net/wiki/spaces/OCNICE/pages/95977592/Updating+MPAS+Framework+and+Components+in+ACME)

I'm also happy to do it, since that is part of my role in integrating MPAS PRs into E3SM

2021-01-13 23:24 UTC, mattdturner commented
@jonbob if you could go ahead and do it for this PR, that would be appreciated.  I'll review the link that you sent, and use the automated scripts from here on out for namelist changes.

2021-01-13 23:31 UTC, jonbob commented
@mattdturner - sounds good. Or I'm always happy to do that as soon as the PR is ready to be tested in E3SM. You can just let me know and I can make the commit for the E3SM scripts

2021-01-14 15:36 UTC, jonbob approved these changes
I ran the automated scripts to make the e3sm bld scripts consistent with the Registry changes, and pushed the results back to this branch. It passes sanity testing after the push

2021-01-14 15:57 UTC, jonbob commented
merged to next

2021-01-15 17:35 UTC, merged

2021-01-15 17:38 UTC, jonbob commented
merged to master. The NML DIFFs from this PR are not yet blessed because a CIME PR went in on the same day and caused NML DIFFs for all tests. The NML blesses from that PR may handle those from this one as well, but I'll leave this open until that takes place.