Ocean global limiting options for FCT vertical tracer advection
E3SM-Project/E3SM pull request #3999
Opened 2020-12-21 17:26 UTC by mark-petersen

See https://github.com/MPAS-Dev/MPAS-Model/pull/774. This adds two new options:
- `config_adv_first_direction = 'horizontal'` (default, bfb with previous) and `'vertical'` (new option)
- `config_activeTracer_vert_limiter = 'standard_FCT'` (bfb with previous) and `'fixed_global_limit'` (proposed new default)

nonBFB

2020-12-21 17:36 UTC, mark-petersen commented
Currently includes changes in #3995. @jonbob could you update the E3SM namelist files here? It should be set to defaults:
```
config_adv_first_direction = 'horizontal'
config_activeTracer_vert_limiter = 'fixed_global_limit'
config_vert_limiter_temperature_min = -1.8
config_vert_limiter_temperature_max = 34
config_vert_limiter_salinity_min = 0
config_vert_limiter_salinity_max = 45
```
Those are all the defaults in `Registry.xml` except `config_activeTracer_vert_limiter = 'fixed_global_limit'`. @vanroekel please confirm these settings.

@mattdturner after that, could you please test standard cases (PEM, PET) with `config_activeTracer_vert_limiter = 'fixed_global_limit'`, and separate tests with `config_adv_first_direction = 'horizontal'` and then `'vertical'`. Then also check bfb with previous using
```
config_adv_first_direction = 'horizontal'
config_activeTracer_vert_limiter = 'standard_FCT'
```
Thanks!

2020-12-21 18:37 UTC, vanroekel commented
only one change
```
config_adv_first_direction = 'vertical'
```

2020-12-22 15:10 UTC, mark-petersen commented
Rebased. Corrected missing `private(k)` in MPAS.

2020-12-23 01:59 UTC, mattdturner commented
I locally modified the namelist files, and ran a few tests on Cori.  Here are the results:
`config_adv_first_direction = ‘vertical’` with `config_activeTracer_vert_limiter = ‘standard_FCT’`
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
```

`config_adv_first_direction = ‘horizontal’` with `config_activeTracer_vert_limiter = ‘standard_FCT’`
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
```

`config_adv_first_direction = ‘vertical’` with `config_activeTracer_vert_limiter = ‘fixed_global_limit’`
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
```

`config_adv_first_direction = ‘horizontal’` with `config_activeTracer_vert_limiter = ‘fixed_global_limit’`
```
PASS:
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
SMS.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_intel
PET_Ln3.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_intel
PEM_Ln9.T62_oQU240.GMPAS-IAF.cori-haswell_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_gnu
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.cori-knl_intel
PET_Ln9.T62_oQU240.GMPAS-IAF.cori-knl_intel
```

No tests failed.  I am going to run the BFB tests in the morning and will report back.

2020-12-23 17:19 UTC, mattdturner commented
The following BFB tests pass if `config_adv_first_direction = ‘horizontal’` and `config_activeTracer_vert_limiter = 'standard_FCT'`:
```
PASS:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
```

If `config_adv_first_direction = 'vertical'` (the default) and `config_activeTracer_vert_limiter = 'standard_FCT'`:
```
FAIL:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
```

If `config_adv_first_direction = ‘horizontal’` and `config_activeTracer_vert_limiter = 'fixed_global_limit'` (the default): 
```
FAIL:
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_intel
SMS.T62_oQU120_ais20.MPAS_LISIO_TEST.compy_pgi
```

So, the code is BFB w/ `config_adv_first_direction = ‘horizontal’` and `config_activeTracer_vert_limiter = 'standard_FCT'`, but not BFB with the defaults

2020-12-23 17:19 UTC, mattdturner approved these changes

2020-12-23 17:54 UTC, mark-petersen commented
@vanroekel what is the priority for this one? #4004 is going onto next today.

2020-12-23 19:32 UTC, vanroekel commented
@mark-petersen this is low priority, given results in testing it's not clear if this is a useful thing to add to the code.  Do you know (also @mattdturner) if this is BFB with E3SM master for 
```
config_adv_first_direction = ‘horizontal’ with config_activeTracer_vert_limiter = ‘standard_FCT’
```
?

2020-12-23 20:44 UTC, mattdturner commented
@vanroekel Yes, this is BFB with E3SM master for 
```
config_adv_first_direction = ‘horizontal’ with config_activeTracer_vert_limiter = ‘standard_FCT’
```

That is just not the default configuration right now in this PR

2020-12-23 22:22 UTC, vanroekel requested changes

2020-12-23 22:22 UTC, vanroekel commented on components/mpas-ocean/bld/namelist_files/namelist_definition_mpaso.xml
> +<entry id="config_activeTracer_vert_limiter" type="character"
Note that for this to work on anvil or chrysalis we need to change ```character``` to ```char*1024```

2020-12-23 22:22 UTC, vanroekel commented on components/mpas-ocean/bld/namelist_files/namelist_definition_mpaso.xml
> +<entry id="config_adv_first_direction" type="character"
For this to work on anvil/chrysalis change ```character``` to ```char*1024```

2020-12-23 22:22 UTC, vanroekel commented on components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
> +<config_activeTracer_vert_limiter>'fixed_global_limit'</config_activeTracer_vert_limiter>
for now, let's change the default back to ```'standard_FCT'```

2020-12-23 22:22 UTC, vanroekel commented on components/mpas-ocean/bld/namelist_files/namelist_defaults_mpaso.xml
> +<config_adv_first_direction>'vertical'</config_adv_first_direction>
let's change the default to ```'horizontal'``` to keep BFB with master

2021-01-04 17:00 UTC, mattdturner commented
@vanroekel I just pushed the namelist changes that you requested

2021-01-13 18:40 UTC, jonbob commented
@mark-petersen, @vanroekel - are we still intending to merge this? If not, can we close it?

2021-01-13 19:03 UTC, vanroekel commented
@jonbob These changes ended up not making differences in coupled testing.  My suggestion is closing it.

2021-01-13 19:05 UTC, closed without merging