Defines core kind for configurations not using CLUBB_SGS
E3SM-Project/E3SM pull request #4167
Opened 2021-03-19 03:50 UTC by singhbalwinder

MMF tests were braking as CLUBB_SGS is not defined for MMF like configurations.
[BFB]

2021-03-19 17:21 UTC, brhillman requested changes
This looks great. One request, can we add `ERS_Ln9_P96x1.ne4pg2_ne4pg2.F-MMF1.eam-crmout` to `e3sm_developer`, or else move it from `e3sm_integration` to `e3sm_developer` so that this is easier to catch before merging PRs in the future?

2021-03-19 17:42 UTC, singhbalwinder commented
I have moved the MMF test from the integration to the developer suite.

2021-03-19 17:45 UTC, brhillman approved these changes
Looks great, thanks Balwinder!

2021-03-19 17:49 UTC, rljacob commented
Going back to when those tests last ran, they only take about 2.5 minutes each so 1 won't add much to developer.

2021-03-22 22:23 UTC, brhillman commented
Hey @singhbalwinder, there's a problem with moving that MMF test to the developer suite. Since it explicitly requests 96 MPI tasks, this will fail on our test platforms that do not have this many processors. I think we should remove the task specification from the test, so the test should instead be just: `ERS_Ln9.ne4pg2_ne4pg2.F-MMF1.eam-crmout`. What do you think?

2021-03-22 22:47 UTC, brhillman approved these changes

2021-03-22 23:50 UTC, brhillman commented
Merged to next.

2021-03-23 18:40 UTC, merged

2021-03-23 18:40 UTC, brhillman commented
Merged to master.