Updates carbon conservation analysis member
E3SM-Project/E3SM pull request #4826
Opened 2022-03-09 17:49 UTC by njeffery

1. tracks individual ocean-ice carbon  fluxes
2. computes accumulated error, relative errors, error bounds over the run
3. adds flag option to end the run if carbon errors exceed bounds
4. Also added three additional diagnostics
5. Adds molecular weight of carbon as a shared constant for all carbon conservation calculations
6. Non-BFB change is a correction in merge-fluxes-bgc which uses the initial ice area to merge BGC fluxes rather than the ice area after step therm 1.

Passes all tests in the sea ice testing suite. BFB in all but runs with active sea ice BGC.

2022-03-14 21:51 UTC, akturner requested changes
This stalls in my tests during the conservation check. I'm investigating this. Also, why is the conservation check now on for the standard physics configuration?

2022-03-14 21:51 UTC, akturner commented on components/mpas-seaice/testing_and_setup/configurations/standard_physics/namelist.seaice
> -    config_AM_conservationCheck_enable = false
Why has this been changed?

2022-03-15 14:41 UTC, akturner commented
@njeffery: MPAS-Seaice stalls in the conservation write in master so this is not an issue with this PR. Switch config_AM_conservationCheck_enable to false and this should pass testing.

2022-03-15 15:08 UTC, njeffery commented
@akturner :  done

2022-03-29 19:40 UTC, akturner approved these changes

2022-03-31 23:37 UTC, jonbob commented
Initial testing failed because the value of config_AM_conservationCheck_carbon_failure_abort was set to a 'false' string instead of a simple logical false. I ran the scripts to autogenerate the bld files from Registry changes and it fixed that issue

2022-04-07 17:33 UTC, rljacob commented
telecon notes:  ready to go.

2022-04-14 17:11 UTC, jonbob commented
test merge passes:
* SMS_Ld2.ne30pg2_r05_EC30to60E2r2.BGCEXP_CNTL_CNPECACNT_1850.chrysalis_intel.elm-bgcexp
* SMS_D_Ld1.T62_oEC60to30v3.DTESTM
except for expected NML DIFFs

2022-04-19 16:27 UTC, jonbob commented
merged to next

2022-04-20 17:21 UTC, merged

2022-04-20 17:33 UTC, jonbob commented
merged to master and expected NML DIFFs blessed