Makefile updates to fix parallel build failures
E3SM-Project/E3SM pull request #4948
Opened 2022-05-13 15:28 UTC by brian-oneill

Update object file dependency definitions in src/mode_init/Makefile and src/shared/Makefile to resolve build errors that occur when building ocean_model with multiple jobs (i.e. 'make -j').

Confirmed successful parallel build from scratch on Summit, Cori, and Chrysalis. No edits to code execution.

2022-05-18 19:10 UTC, philipwjones requested changes
@brian-oneill  - Thanks for updating these. While testing, I ran into another dependency so I grep'd on "use ocn_" in the src/shared directory and updated the Makefile there with all of the use-based dependencies. With that version, everything worked fine. I pushed that onto my fork of E3SM in a branch of the same name (philipwjones:brian-oneill/ocean/makefile-updates ) so you can either just copy that version of the shared Makefile, merge my version into yours or however you want to do it. Then this should be good to go.

2022-05-19 13:51 UTC, philipwjones approved these changes
Great, thanks @brian-oneill  Approved based on quick QU240 tests and successful parallel builds across supported machines.

2022-05-27 16:45 UTC, jonbob commented
Passes sanity testing, merged to next

2022-06-01 16:17 UTC, merged

2022-06-01 16:18 UTC, jonbob commented
merged to master