Adds omp critical directives for ice warnings
E3SM-Project/E3SM pull request #5062
Opened 2022-07-06 17:41 UTC by singhbalwinder

While running some ensemble members for v2 on Cori-KNL, we occasional hit errors like
"forrtl: severe (151): allocatable array is already allocated" pointing to ice_warnings.f90
file. Adding an "omp critical" section in this file fixes these errors.

[BFB]

2022-07-06 17:53 UTC, ambrad requested changes
Even though it won't change the threading behavior, for precision I recommend making this a named critical region, something like:
```f90
!$omp critical ice_warnings_add_warning
...
!$omp end critical ice_warnings_add_warning
```

2022-07-06 18:01 UTC, singhbalwinder commented
Thanks, @ambrad for this useful suggestion and the fix itself! I have named the critical section now.

2022-07-06 18:02 UTC, ambrad commented
@singhbalwinder you'll need to put parens around the names; sorry I forgot those when suggesting the names.

2022-07-06 19:08 UTC, ambrad approved these changes

2022-07-06 19:10 UTC, singhbalwinder commented
No worries, I just fixed it.

2022-07-12 21:44 UTC, akturner approved these changes
Approved by visual inspection

2022-07-14 22:07 UTC, jonbob commented
passed sanity testing and PET_Ln5.ne4_oQU240.F2010.chrysalis_intel.allactive-mach-pet

merged to next

2022-07-18 15:12 UTC, merged

2022-07-18 15:13 UTC, jonbob commented
merged to master