Adds omp critical directives for ice warnings (for maint2.0)
E3SM-Project/E3SM pull request #5063
Opened 2022-07-06 17:46 UTC by singhbalwinder

While running some ensemble members for v2 on Cori-KNL, we occasional hit errors like
"forrtl: severe (151): allocatable array is already allocated" pointing to ice_warnings.f90
file. Adding an "omp critical" section in this file fixes these errors.

[BFB]

2022-07-06 17:54 UTC, ambrad requested changes
See my comment in the PR to the master branch.

2022-07-06 17:58 UTC, ambrad approved these changes

2022-07-06 18:01 UTC, ambrad commented
Oh, whoops, you need parentheses around the names.

2022-07-06 19:08 UTC, ambrad approved these changes

2022-07-06 19:10 UTC, ambrad approved these changes

2022-07-12 21:42 UTC, akturner approved these changes
Approved from visual inspection

2022-07-18 21:29 UTC, jonbob commented
@golaz - I merged the companion PR to master already but would appreciate your OK before pushing this to maint-2.0, whenever you have time. Thanks!

2022-07-21 17:36 UTC, rljacob commented
As long as it doesn't change answers, I think you can go ahead with the maint-2.0 merge.

2022-07-25 21:22 UTC, merged

2022-07-25 21:24 UTC, jonbob commented
merged to maint-2.0