fates api 24
E3SM-Project/E3SM pull request #5092
Opened 2022-07-21 14:20 UTC by rgknox

This set of changes enables coupling with FATES API 24.  This introduces the ability of FATES to dictate the number of veg-patches used on the natural land unit, an updated FATES parameter file format, hooks to enable fates wood harvest product fluxes, and hooks for a new crown damage module.

2022-07-23 19:38 UTC, rgknox commented
land developer tests on cori pass:
/global/cscratch1/sd/rgknox/e3sm_tests/E2ba9fa8333-Fdef6b3e7-fates-api24-v2

All fates tests have expected NLCOMP and BASELINE differences
All non-fates tests are B4B with base with some timing differences which I believe are due to machine performance variability

2022-08-04 06:00 UTC, bishtgautam commented on cime_config/tests.py
> +            #"SMS_Ld30.f45_f45.IELMFATES.elm-fates_damage", # tree-damage coming soon
Can this test be turned on?

2022-08-04 13:44 UTC, rgknox commented on cime_config/tests.py
> +            #"SMS_Ld30.f45_f45.IELMFATES.elm-fates_damage", # tree-damage coming soon
not yet, the model will gracefully fail.  The fates tree damage module will be in soon though.  I can remove this if its clutter, no problem.

2022-08-12 18:04 UTC, rgknox commented
Thanks for comments @bishtgautam , I think I've addressed them

2022-08-12 18:40 UTC, bishtgautam approved these changes

2022-08-12 18:41 UTC, bishtgautam commented
@rgknox Is this PR BFB?

2022-08-12 18:44 UTC, bishtgautam requested changes
Since the new test is not active, can you please remove `components/elm/cime_config/testdefs/testmods_dirs/elm/fates_damage`?

2022-08-12 20:10 UTC, rgknox commented
I can. This module is in progress in FATES, we do plan on having a test for it.

2022-08-18 14:07 UTC, rgknox commented
@bishtgautam , removed the damage test defs

2022-08-18 16:05 UTC, bishtgautam approved these changes

2022-08-25 17:23 UTC, rljacob commented
@bishtgautam is this ready to merge?

2022-08-25 17:34 UTC, peterdschwartz commented
I've merged to my local next branch and am just waiting on test suite results.

2022-08-25 17:45 UTC, bishtgautam approved these changes

2022-08-30 20:36 UTC, peterdschwartz commented
merged to next

2022-08-31 18:38 UTC, merged

2022-08-31 18:45 UTC, peterdschwartz commented
Merged to master.