Ascent config changes
E3SM-Project/E3SM pull request #5109
Opened 2022-08-03 23:54 UTC by jgfouca

We discovered these were needed for SCREAM.

[BFB]

2022-08-03 23:54 UTC, jgfouca commented on cime_config/machines/config_machines.xml
> +        <arg name="smpiargs">--smpiargs="-gpu"</arg>
All this was needed just to express that smpiargs=gpu is needed for GPU runs.

2022-08-04 00:01 UTC, ambrad commented
Looks like xmllint in the CI is flagging something.

2022-08-04 01:03 UTC, amametjanov requested changes
I'm guessing this is for `ne30_ne30.F2010-SCREAMv1.ascent_gnugpu` runs.
Please reduce duplication with an env-var.

2022-08-04 01:03 UTC, amametjanov commented on cime_config/allactive/config_pesall.xml
> +          <ntasks_wav>-4</ntasks_wav>
This might affect E3SM runs too: i.e. without `pes compset=.*SCREAM.*` limiter. Let's see what testing says.

2022-08-04 16:04 UTC, jgfouca commented
Thanks, @amametjanov ! That's a neat trick to leverage the environment to achieve conditional args in the mpirun args.

I also made a .*SCREAM.* selector in the pes as you requested.

2022-08-04 16:21 UTC, jgfouca commented
OK, `preview_run` seems to indicate everything is working as intended on ascent. GPU compilers get the smpiarg argument and non-GPU don't.

2022-08-04 18:05 UTC, amametjanov approved these changes

2022-08-04 18:05 UTC, amametjanov commented on cime_config/allactive/config_pesall.xml
> +  <grid name="a%ne30np4">
Either revert to `a%ne30np4.pg2` or change all comments in this block to reflect any `pg` modifier.

2022-08-04 18:05 UTC, amametjanov commented on cime_config/allactive/config_pesall.xml
> +        <comment>summit|ascent: BGC compset on ne30np4.pg2 grid</comment>
Update comment and include `SCREAM`: this comment shows up in env_mach_pes.xml and can be helpful.

2022-08-04 18:14 UTC, ambrad commented
Just noting here for future reference, if needed, that removing `.pg2` was done to permit both np4 and pg2 physics-grid configurations to trigger this block of XML, not just pg2.

2022-08-04 18:29 UTC, merged