Fixes conservation error from removal of thin ice by adjust_enthalpy
E3SM-Project/E3SM pull request #5207
Opened 2022-09-26 20:23 UTC by akturner

Fixes conservation error from removal of thin ice in thickness_changes in the column package by adjust_enthalpy

Fixes https://github.com/E3SM-Project/E3SM/issues/5124

[Non-BFB]

2022-09-26 20:57 UTC, eclare108213 approved these changes
Looks good, thank you.

2022-09-27 04:06 UTC, rljacob commented
Is this non-BFB even for F-cases that use the thermo-only MPAS-seaice?

2022-09-27 16:05 UTC, mkstratos commented
This doesn't seem to fix the issue in the F2010 compset test with dtime=1, but the previous fix did.

My test is here (I think I set it up correctly): `/lcrc/group/e3sm/ac.mkelleher/scratch/chrys/TSC.ne4_oQU240.F2010.chrysalis_intel.G.20220927_085853_dh4wu4`

2022-09-28 18:05 UTC, jonbob commented
@mkstratos -- I can confirm that our simplified test also fails.

2022-09-29 18:59 UTC, akturner commented
@mkstratos :Apologies, should now work

2022-09-29 21:32 UTC, jonbob commented
Our simplified test did pass with your latest commit, @akturner -- thanks! @mkstratos, could you please test as well whenever you get a chance?

2022-09-30 12:50 UTC, mkstratos approved these changes
Looks good to me, the TSC baseline is generated for F2010, thanks @akturner!

2022-09-30 15:28 UTC, njeffery commented
@akturner : I'm wondering about the salt flux to the ocean.  There is no corresponding mass flux and the salt flux is only defined based on a reference salinity.

2022-10-12 17:35 UTC, akturner commented
@njeffery: I removed the conservation correction for salt.

2022-10-12 19:41 UTC, njeffery approved these changes

2022-10-20 16:17 UTC, jonbob commented
Because this is non-BFB, I ran two ten-year tests -- one without and one with this PR. MPAS-Analysis comparison output is at:
[20221017.PR5207.anvil](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.jwolfe/20221017.PR5207.anvil/html/)

@xylar or @mark-petersen -- could you please check this from the ocean perspective? And @eclare108213 or @njeffery -- could you please make sure the seaice looks like it's not significantly impacted?

2022-10-20 17:01 UTC, njeffery commented
@jonbob : the sea ice looks a fair bit thicker. Are the conservation analysis members enabled in your run?  Probably worth double checking energy conservation.  Could point me to your run directory?

2022-10-20 17:05 UTC, njeffery commented
found it!  /lcrc/group/acme/ac.jwolfe/scratch/anvil/20221017.PR5207.anvil

2022-10-20 17:05 UTC, eclare108213 reviewed
I don't really understand why the salt flux should not be updated along with the energy flux.  The current modifications fix the problem with F-cases crashing, which is great.  This change also affects the full model runs and is an improvement in terms of energy conservation.  I'm wondering whether the salt flux should also be updated. This could be done in a separate PR, to keep this one moving. On the other hand, the ice volume changes in @jonbob's tests are larger than I would expect.  Could the mismatch between salt and heat fluxes be accentuating these differences?

2022-10-20 17:14 UTC, njeffery commented on components/mpas-seaice/src/column/ice_therm_vertical.F90
> +                                    fhocnn,    fsaltn,   &
Part of the problem is that only the enthalpy of the thin ice is removed here, not it's volume.   If the volume were removed too, then both a salt and fresh water flux could be added consistently.

2022-10-20 17:14 UTC, jonbob commented
Sorry @njeffery -- I bet I didn't. I'm happy to rerun both with the conservation analysis members on

2022-10-27 19:52 UTC, eclare108213 requested changes
The simulation changes are more substantial than expected, which I think should be understood before this is merged.  In my opinion, the mass (salt and fresh water) fluxes should be updated consistently with the enthalpy adjustment.  If the simulation still changes a lot, then look at conservation diagnostics to track it down.

2022-11-01 17:21 UTC, closed without merging