Add F2010-SCREAMv1 test to e3sm_gpucxx suite
E3SM-Project/E3SM pull request #5495
Opened 2023-03-02 15:39 UTC by brhillman

Add F2010-SCREAMv1 test to e3sm_gpucxx suite to get test coverage on GPU for EAMxx codebase in main E3SM repo.

[BFB]

2023-03-03 18:07 UTC, xyuan approved these changes
I have tested on Summit using both cpu and gpu, and it works fine, thanks.

2023-03-07 14:50 UTC, brhillman commented
Thanks @amametjanov this actually passes for me on the SCREAM repo, and confirmed it fails with a local master merge into E3SM on summit. I'll try to figure out what's going on with the master merge.

2023-03-07 15:20 UTC, brhillman commented
Okay, I see what happened. It looks like #5481 changed some things in hommexx that haven't been fixed upstream in E3SM yet. The fixes are on the SCREAM repo, so I will need to open another PR to pull those into E3SM I think.

2023-03-14 19:11 UTC, rljacob approved these changes

2023-04-05 19:31 UTC, rljacob requested changes
There should not be 356 commits for such a simple addition.

2023-04-05 22:02 UTC, brhillman commented
@rljacob I had to pull in a scream->e3sm merge because there were conflicts between the two repos since this PR was opened that prevented SCREAMv1 from building on the E3SM repo. I can move this to a separate PR, or rename this one to reflect this. Was waiting on my tests to update this PR (which just passed).

2023-04-05 22:59 UTC, rljacob commented
Please make a separate PR.

2023-04-05 23:22 UTC, rljacob commented
If you need to resync SCREAM with E3SM and its 300+ commits, that should be its own PR.

2023-04-05 23:28 UTC, brhillman commented
This requires #5582 to fix SCREAMv1 build errors.

2023-04-05 23:30 UTC, brhillman commented
> If you need to resync SCREAM with E3SM and its 300+ commits, that should be its own PR.

Done. My reasoning here was to consider this PR the upstream merge, and as a side effect add the test to make sure it doesn’t break again, rather than considering the upstream merge the effect. In any event, #5582 is opened to bring EAMxx up to date, then this PR will just add the test.

2023-04-05 23:37 UTC, rljacob approved these changes

2023-05-26 02:14 UTC, amametjanov commented
Do we need to add machine-specific cmake in `components/eamxx/cmake/machine-files/`?
From a JLSE run:
```
-- Found scream component
No macro file found: /gpfs/jlse-fs0/projects/climate/azamat/scratch/J/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.jlse_oneapi-ifxgpu.JNextGpucxx20230525_060459/cmake_macros/LINUX.cmake
No macro file found: /gpfs/jlse-fs0/projects/climate/azamat/scratch/J/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.jlse_oneapi-ifxgpu.JNextGpucxx20230525_060459/cmake_macros/jlse.cmake
No macro file found: /gpfs/jlse-fs0/projects/climate/azamat/scratch/J/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.jlse_oneapi-ifxgpu.JNextGpucxx20230525_060459/cmake_macros/oneapi-ifxgpu_LINUX.cmake
No macro file found: /gpfs/jlse-fs0/projects/climate/azamat/scratch/J/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.jlse_oneapi-ifxgpu.JNextGpucxx20230525_060459/cmake_macros/oneapi-ifxgpu_jlse.cmake
CMake Error at cmake/build_eamxx.cmake:39 (include):
  include could not find requested file:

    /gpfs/jlse-fs0/projects/climate/testing/E3SM/components/eamxx/cmake/machine-files/jlse.cmake
Call Stack (most recent call first):
  CMakeLists.txt:120 (build_eamxx)
```
Similar error on Crusher: https://my.cdash.org/viewTest.php?buildid=2341352

Works on Ascent: https://my.cdash.org/viewTest.php?buildid=2341401

2023-07-06 17:34 UTC, rljacob commented
notes:  needs some syncing and restesting.  @brhillman will do.

2023-07-12 05:15 UTC, rljacob commented
@brhillman is this ready now?

2023-07-14 22:28 UTC, amametjanov commented
If I copy `crusher-scream-gpu.cmake` to `components/eamxx/cmake/machine-files/crusher.cmake`, the build succeeds, but the run fails during atm-init with
```
$ tail /lustre/orion/cli115/proj-shared/azamat/e3sm_scratch/crusher/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.crusher_crayclanggpu.G.20230714-chk-new-scream-gputest4/run/e3sm.log.350998.230714-173930 
0: (seq_comm_printcomms)    31     0     1     1  ALLESPID:
0: (seq_comm_printcomms)    32     0     8     1  CPLALLESPID:
0: (seq_comm_printcomms)    33     0     1     1  ESP:
0: (seq_comm_printcomms)    34     0     8     1  CPLESP:
0: (seq_comm_printcomms)    35     0     1     1  ALLIACID:
0: (seq_comm_printcomms)    36     0     8     1  CPLALLIACID:
0: (seq_comm_printcomms)    37     0     1     1  IAC:
0: (seq_comm_printcomms)    38     0     8     1  CPLIAC:
srun: error: crusher188: tasks 0-7: Bus error
srun: Terminating StepId=350998.0
```

2023-07-16 16:26 UTC, sarats commented
Just FYI. 
Testing with PR #5745, https://my.cdash.org/test/85523812 results in errors:

Essentially, looking for non-existent macro files (Linux.cmake, crusher.cmake and crayclanggpu_Linux.cmake).
```
165 No macro file found: /lustre/orion/cli115/proj-shared/sarat/e3sm_scratch/crusher/J/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.crusher_crayclanggpu.C.JNextGpucxx20230714_154451/cmake_macros/Linux.cmake
166 No macro file found: /lustre/orion/cli115/proj-shared/sarat/e3sm_scratch/crusher/J/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.crusher_crayclanggpu.C.JNextGpucxx20230714_154451/cmake_macros/crusher.cmake
167 No macro file found: /lustre/orion/cli115/proj-shared/sarat/e3sm_scratch/crusher/J/ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.crusher_crayclanggpu.C.JNextGpucxx20230714_154451/cmake_macros/crayclanggpu_Linux.cma    ke
```

2023-08-10 17:29 UTC, rljacob commented
note:  build fail is being looked at.

2023-08-10 21:40 UTC, brhillman commented
So, the test passes with `crusher-scream-gpu_crayclang-scream` for machine_compiler. I guess one option would be to separate the scream and mmf tests into two different suites and use the scream-specific machine/compiler combination for this particular test.

2023-08-10 22:01 UTC, rljacob commented
That's good to know but we want to move away from the scream-specific compiler settings.

2023-08-24 16:40 UTC, rljacob commented
@jgfouca this is the PR about the scream and E3SM build.

2023-10-12 17:28 UTC, rljacob commented
waiting on cmake refactor.

2023-12-04 19:48 UTC, rljacob commented
@jgfouca any progress on getting scream and e3sm machine/compiler descriptions unified?

2023-12-04 20:28 UTC, jgfouca commented
@rljacob , currently waiting on a couple CIME PRs and then I will do a CIME update. Once that is done, I will do an upstream merge to SCREAM, which will force me to sort out the remaining build system issues.

2024-01-29 17:50 UTC, rljacob commented
@brhillman I believe this modified suite will now build and run after merging to next.  Can you confirm?

2024-02-01 18:26 UTC, rljacob commented on cime_config/tests.py
> +                 "ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1",
why ERP?

2024-02-01 20:07 UTC, rljacob commented on cime_config/tests.py
> +                 "ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1",
Nevermind.  There are ERP tests in the SCREAM suite.

2024-02-01 20:08 UTC, rljacob commented
@amametjanov can you verify the new version of this suite will build on a system running gpucxx ?

2024-02-01 20:09 UTC, rljacob commented
It probably needs to be rebased to get Jim's recent build system changes.

2024-03-07 04:21 UTC, amametjanov commented
I'm trying on pm-gpu on latest E3SM `master` with
```
./cime/scripts/create_test --machine pm-gpu --compiler gnugpu ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1
```
but getting
```
CMake Error at eamxx/src/physics/rrtmgp/CMakeLists.txt:39 (target_link_libraries):
  INTERFACE library can only be used with the INTERFACE keyword of
  target_link_libraries


-- Disabling all warnings for target yakl
CMake Error at /global/u2/a/azamat/saul/E3SM/externals/ekat/cmake/EkatUtils.cmake:102 (target_compile_options):
  target_compile_options may only set INTERFACE properties on INTERFACE
  targets
Call Stack (most recent call first):
  eamxx/src/physics/rrtmgp/CMakeLists.txt:40 (EkatDisableAllWarning)


-- Found CUDA: /opt/nvidia/hpc_sdk/Linux_x86_64/22.7/cuda/11.7 (found version "11.7")
CMake Error at /global/u2/a/azamat/saul/E3SM/externals/ekat/cmake/EkatSetCompilerFlags.cmake:379 (target_compile_options):
  target_compile_options may only set INTERFACE properties on INTERFACE
  targets
Call Stack (most recent call first):
  eamxx/src/physics/rrtmgp/CMakeLists.txt:53 (SetCudaFlags)

```

2024-03-07 17:40 UTC, jgfouca commented
@amametjanov , I've fixed that on the EAMXX fork. I will do a downstream merge soon.

2024-05-02 17:36 UTC, jgfouca commented
The downstream merge is done, merged to next.

2024-05-08 16:43 UTC, rljacob commented
The only place we run this test is pm-gpu and looks like SCREAM has a runtime error:
https://my.cdash.org/viewTest.php?onlyfailed&buildid=2558361

At least its not build time!

2024-05-08 17:02 UTC, ndkeen commented
Rob that job looks like it ran out of walltime

2024-05-15 21:42 UTC, rljacob commented
@jgfouca how do we increase the walltime for the scream test?

2024-05-15 22:02 UTC, jgfouca commented
@rljacob , there are a few ways. This new test in the suite `e3sm_gpucxx` which does not have "time" field. We could add this field and set it to something long enough to give it a chance to finish. As an alternative, if this test is only too slow on one platform, we can go to that machine, run the test by hand `./create_test $test --walltime=4:00:00`. If it passes, it will store the runtime under the $baseline/walltimes area and our "smart" walltime system will give that time the highest precedence when choosing a default time.

2024-05-15 22:27 UTC, rljacob commented
Lets do the second option but wait until pm comes back online.

2024-05-15 23:15 UTC, ndkeen commented
Note that when I try this same test on muller-gpu (generally same as pm-gpu), I get an error and a hang.  We would not expect any ne4 test to take much time, so maybe don't increase the walltime for the test.

```
2: (GTL DEBUG: 2) cuIpcGetMemHandle: invalid argument, CUDA_ERROR_INVALID_VALUE, line no 97
```

2024-05-17 19:47 UTC, jgfouca commented
Should I merge to master or hold off?

2024-05-29 02:29 UTC, rljacob commented
@ndkeen is the one SCREAM test in this suite still running out time?

2024-05-29 03:00 UTC, ndkeen commented
If I recall, I think we found some issue with the test hanging.  

When I tried it just now, I get a build error:
```
components/eamxx/src/share/atm_process/atmosphere_process_dag.cpp(149): error: class "ekat::units::Units" has no member "get_string"
          s += " [" + fid.get_units().get_string() + "]";
                                      ^

```

2024-05-29 17:48 UTC, rljacob commented
@bartgol since Jim is on vacation, could you take a look at the above build error on pm-gpu?

2024-05-30 15:12 UTC, bartgol commented
Oh, wait, this has the new ekat, but an old EAMxx. EAMxx is still using code from an old ekat. We need to update eamxx first. Perhaps the cleanest thing is to remove the branch from next, hard reset the branch to track an up-to-date eamxx, and then remerge to next.

2024-05-30 15:47 UTC, rljacob commented
I'd rather have an eamxx update in a separate PR.  Then when that is on next, this should work.

2024-05-30 16:50 UTC, bartgol commented
That's fine with me. And now, let's draw straws! :)

Jokes aside, how soon do we want this to be integrated?

2024-06-03 21:43 UTC, rljacob commented
I'm really sick of seeing this open PR so an eamxx downstream merge soon would be good.  But I think there is an upstream still pending over in scream.  @jgfouca can you push that along?

2024-06-10 20:49 UTC, bartgol commented
@rljacob the downstream merge in the scream repo should move along today. There was a failing test due to a bad auto-resolution of a conflict. Should be fixed now, and tests should be passing on the next AT round (mappy is a bit backed up due to it being offline for a few days).

2024-07-13 00:43 UTC, rljacob commented
After the downstream merge in https://github.com/E3SM-Project/E3SM/pull/6489 there's no longer a kokkos build error but there is an error from COSP.  @jgfouca can you look at it next week?

2024-08-07 03:42 UTC, rljacob commented
@zyuying can you look at the build error from your COSP changes when building scream on pm-gpu?

2024-08-21 17:16 UTC, brhillman commented
@rljacob this should now fix the SCREAMv1 build error associated with the COSP updates.

2024-08-22 16:18 UTC, merged