Add new SOwISC12to60E3r1 ocean and sea-ice mesh
E3SM-Project/E3SM pull request #5935
Opened 2023-09-19 07:53 UTC by xylar

Long name: SOwISC12to60kmL64E3SMv3r1

This version of the Southern Ocean Regionally Refined Mesh (SORRM) has the same distribution of resolution as in the E3SM v2 version of the mesh [SOwISC12to60E2r4](https://github.com/MPAS-Dev/compass/pull/37), including:
* 12 km resolution around Antarctica
* 45 km resolution at southern mid-latitudes
* 30 km resolution at the equator and the north Atlantic
* 60 km resolution in the north Pacific
* 35 km resolution in the Arctic

It matches the EC30to60 (#5927) mesh except in the Southern Ocean and north Atlantic.

This is a proposed E3SM v3 (E3) mesh for polar (formerly cryosphere) simulations.  It is also being considered for flagship coupled simulations because of its strong AMOC.  This is revision 1 (r1) of the mesh, since we caught and fixed the issues with Greenland topography (seen in earlier revisions of EC and Icos meshes) before any substantial testing was performed.

The mesh was created using [compass](https://github.com/MPAS-Dev/compass), specifically this tag: https://github.com/MPAS-Dev/compass/releases/tag/mesh_SOwISC12to60E3r1

A G-case with data iceberg melt fluxes (DIB) and data ice-shelf melt fluxes (DISMF) has been run for 30 years, with MPAS-Analysis output available here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.jwolfe/20230905.G-test.SOwISC12to60E3r1.anvil/html/

The mesh and the G-case results are being reviewed here:
https://acme-climate.atlassian.net/wiki/spaces/OO/pages/3894181889/Review+SOwISC12to60E3r1

A B-case will begin shortly and analysis will be posted here and on the review page as soon as it is available.

2023-09-19 07:55 UTC, xylar commented
This branch is based off of #5927 and will be rebased after that gets merged.

Relevant discussion can be found at https://github.com/E3SM-Ocean-Discussion/E3SM/pull/61

2023-09-19 19:51 UTC, mark-petersen approved these changes
Reviewed mesh, coastlines, critical passages, and MPAS-Analysis simulation results.

2023-09-19 21:41 UTC, proteanplanet approved these changes
Coastlines, shallow bathymetry, through-flow regions, and cavity geometry have been checked.

2023-10-04 01:23 UTC, darincomeau approved these changes

2023-11-14 15:30 UTC, rljacob requested changes
bilin maps need to be redone with TempestRemap.  Map names need to be changed to match naming convention.

2023-11-15 22:22 UTC, jonbob commented
I made updated domain and mapping files, changed config_grids.xml to match, and staged them for testing on the local inputdata space on lcdc. I also ran smoke tests successfully for:
* T62_SOwISC12to60E3r1.CMPASO-IAF
* TL319_SOwISC12to60E3r1.GMPAS-JRA1p5
* ne30pg2_r05_SOwISC12to60E3r1.WCYCL1850
* ne30pg2_r05_SOwISC12to60E3r1.WCYCL1850 with new nonlinear mapping file map_ne30pg2_to_SOwISC12to60E3r1_trfvnp2.20231115.nc

2023-11-15 22:23 UTC, jonbob commented
@rljacob -- can you please check the new domain and mapping files?

2023-11-15 23:03 UTC, darincomeau commented
I just added a commit to have this mesh use the previous SORRM PE layouts at LCRC.

2023-11-16 18:08 UTC, darincomeau commented
I'm getting `FAIL SMS.TL319_SOwISC12to60E3r1.GMPAS-JRA1p5.anvil_intel RUN time=440`. Looking into it...

2023-11-16 19:25 UTC, jonbob commented
@darincomeau -- maybe it's related to PR #6069, which has fixes to the mpas_io code? But I'm also suspicious that it's a memory issue because it's only running on four anvil nodes?

2023-11-16 19:49 UTC, darincomeau commented
Thanks @jonbob . I first ran into the error trying to run a G-case on 20 anvil nodes, so I then went back to do the `SMS` test. I'm trying a `SMS_D.TL319_ECwISC30to60E3r2.GMPAS-JRA1p5.anvil_intel` test now.

2023-11-16 21:18 UTC, darincomeau commented
`SMS_D.TL319_SOwISC12to60E3r1.GMPAS-JRA1p5.chrysalis_intel` runs.

I think there's an issue with G-cases in general on Anvil. I've been testing this branch and master, with `SOwISC12to60E3r1` and `ECwISC30to60E3r2`, and every combination dies in init on Anvil (both with `SMS` test and running a G-case on 20 nodes, so memory shouldn't be the issue). The same combinations on Chrysalis run.

2023-11-17 03:22 UTC, rljacob commented on cime_config/config_grids.xml
> +      <map name="ATM2OCN_VMAPNAME">cpl/gridmaps/TL319/map_TL319_to_SOwISC12to60E3r1_patch.20231115.nc</map>
This should be "esmfpatch"

2023-11-17 03:23 UTC, rljacob commented on cime_config/config_grids.xml
> +    </gridmap>
These should be "cstmnn" instead of "smoothed"

2023-11-17 03:24 UTC, rljacob commented on cime_config/config_grids.xml
> +    </gridmap>
These should be "cstmnn" instead of "smoothed".

2023-11-17 03:24 UTC, rljacob commented on cime_config/config_grids.xml
> +    </gridmap>
These should be "cstmnn" instead of "smoothed".

2023-11-20 00:56 UTC, xylar commented
I'm putting this in draft mode because I just discovered a bug in `landIceMask` (which affects the initial condition as well as several mapping files) over the weekend.

https://github.com/MPAS-Dev/compass/pull/732

2023-11-20 16:59 UTC, xylar commented
Closing this because of the bug above.  Will make a new version of the mesh without the bug.

2023-11-20 16:59 UTC, closed without merging