Introduce MOAB coupler interfaces and update moab driver
E3SM-Project/E3SM pull request #5979
Opened 2023-10-10 04:48 UTC by rljacob

2023-10-20 21:38 UTC, rljacob commented
@jonbob @bishtgautam @wlin7 @liho745 : you only need to look at the mods to components.  @jgfouca Just look at build system mods.

2023-10-20 21:41 UTC, jgfouca requested changes
I think you can get rid of the MOAB_PATH stuff in the cmake_macros. You are setting MOAB_ROOT in the config_machines.xml environment, which should be sufficient to activate and find MOAB.

2023-10-20 21:43 UTC, jgfouca commented on components/cmake/build_model.cmake
> +      message("JGF adding include directories ${MOAB_INCLUDE_DIRS}")
You can get rid of my debugging print.

2023-10-20 21:43 UTC, jgfouca commented on components/cmake/build_model.cmake
> +      message("JGF adding include directories ${MOAB_INCLUDE_DIRS}")
You can get rid of my debugging print.

2023-10-20 22:14 UTC, bishtgautam commented
@rljacob An overview question: Why isn't the big `#ifdef HAVE_MOAB` in [components/elm/src/cpl/lnd_comp_mct.F90](https://github.com/E3SM-Project/E3SM/pull/5979/files#diff-dcaa702776bbd34ce3a03cb4e3a731f944062eced731f6106b30a101ca949c21R834-R1645) put in a new file `components/elm/src/cpl/lnd_comp_moab.F90`?

2023-10-20 23:37 UTC, rljacob commented
Because we're still running the mct and moab parts at the same time.   The separation will be done later.

2023-10-30 19:32 UTC, rljacob commented
Forgot to mention how to run this.  On Chrysalis, use "--res ne4pg2_oQU480 --compset WCYCL1850NS --driver moab" in your create_newcase command.

2023-10-30 20:24 UTC, rljacob commented
@jgfouca the particular version of master this started from still needs MOAB_PATH in the cmake macros or there's a build error early:  
```
/gpfs/fs1/home/jacob/E3SMmb/cime/scripts/Wne4pgmb4/Tools/Makefile:244: *** MOAB_PATH must be defined when using moab driver.  Stop.
ERROR: cat: Filepath: No such file or directory
```
I'll remove those in a follow-up PR.

2023-10-30 20:27 UTC, jgfouca commented
@rljacob, why not do an upstream merge to get onto latest master? It looks like there are conflicts to resolve so you'll have to do this anyway.

2023-10-30 20:30 UTC, rljacob commented
I prefer to resolve conflicts during the merge unless there's a bunch of them.  I already merged master to this branch once for some build things.

2023-11-02 19:01 UTC, rljacob commented
@jgfouca I did a test-merge to next and the conflicts are trivial.   Also I removed those debugging prints from cmake.

2023-11-02 19:03 UTC, jgfouca approved these changes

2023-11-14 15:14 UTC, rljacob commented
@jonbob @bishtgautam @liho745 please review.

2023-11-30 22:50 UTC, jonbob commented on components/mpas-ocean/driver/ocn_comp_mct.F
@rljacob -- it doesn't make more sense to have separate ocn_comp_mct and ocn_comp_moab files?

2023-12-01 01:27 UTC, rljacob commented on components/mpas-ocean/driver/ocn_comp_mct.F
Gautum had the same question about lnd_comp_mct.  We're keeping one source while the MCT-MOAB verification code is in place.  They'll be separated when that's removed.

2023-12-01 16:16 UTC, bishtgautam approved these changes
Land changes look good.

2023-12-01 17:08 UTC, liho745 approved these changes
River-related changes look good.

2023-12-01 20:04 UTC, jonbob approved these changes
Looks good from a visual inspection

2023-12-04 19:54 UTC, rljacob commented
@wlin7 if you want any changes, let me know before Wednesday.  I'm going to merge it then.

2023-12-20 03:19 UTC, rljacob commented
merged to next

2023-12-21 17:41 UTC, merged

2023-12-21 21:48 UTC, rljacob commented
For the record here are the files that merged cleanly ("Changes to be committed"), files that had to have conflicts fixed ("Unmerged paths"), and files that needed further modification ("Changes not staged") to work with the new build system.

```
Changes to be committed:
	modified:   components/CMakeLists.txt
	modified:   components/cice/bld/config_files/definition.xml
	modified:   components/cmake/find_dep_packages.cmake
	modified:   components/eam/bld/config_files/definition.xml
	modified:   components/eam/bld/configure
	modified:   components/eam/cime_config/buildnml
	modified:   components/eam/src/cpl/atm_comp_mct.F90
	modified:   components/eam/src/dynamics/se/dyn_comp.F90
	new file:   components/eam/src/dynamics/se/semoab_mod.F90
	modified:   components/elm/bld/config_files/config_definition.xml
	modified:   components/elm/src/cpl/lnd_comp_mct.F90
	modified:   components/elm/src/main/surfrdMod.F90
	modified:   components/elm/src/utils/domainMod.F90
	modified:   components/mosart/bld/build-namelist
	modified:   components/mosart/bld/namelist_files/namelist_defaults_mosart.xml
	modified:   components/mosart/bld/namelist_files/namelist_definition_mosart.xml
	modified:   components/mosart/cime_config/testdefs/testmods_dirs/mosart/mos_usrdat/user_nl_mosart
	modified:   components/mosart/cime_config/testdefs/testmods_dirs/mosart/sediment/shell_commands
	modified:   components/mosart/cime_config/testdefs/testmods_dirs/mosart/sediment/user_nl_mosart
	modified:   components/mosart/cime_config/testdefs/testmods_dirs/mosart/unstructure/user_nl_mosart
	modified:   components/mosart/src/cpl/rof_comp_mct.F90
	modified:   components/mosart/src/riverroute/RtmMod.F90
	modified:   components/mosart/src/riverroute/RtmVar.F90
	modified:   components/mpas-framework/Makefile
	modified:   components/mpas-framework/src/CMakeLists.txt
	modified:   components/mpas-framework/src/Makefile
	modified:   components/mpas-framework/src/driver/mpas_subdriver.F
	modified:   components/mpas-framework/src/framework/Makefile
	new file:   components/mpas-framework/src/framework/mpas_moabmesh.F
	modified:   components/mpas-ocean/driver/ocn_comp_mct.F
	modified:   driver-mct/cime_config/config_component.xml
	modified:   driver-moab/cime_config/buildexe
	new file:   driver-moab/cime_config/buildlib_cmake
	modified:   driver-moab/cime_config/buildnml
	modified:   driver-moab/cime_config/config_component.xml
	modified:   driver-moab/cime_config/config_component_cesm.xml
	modified:   driver-moab/cime_config/config_component_e3sm.xml
	modified:   driver-moab/cime_config/config_pes.xml
	modified:   driver-moab/cime_config/namelist_definition_drv.xml
	modified:   driver-moab/cime_config/namelist_definition_drv_flds.xml
	modified:   driver-moab/cime_config/namelist_definition_modelio.xml
	modified:   driver-moab/main/cime_comp_mod.F90
	modified:   driver-moab/main/cime_driver.F90
	modified:   driver-moab/main/component_mod.F90
	modified:   driver-moab/main/component_type_mod.F90
	modified:   driver-moab/main/cplcomp_exchange_mod.F90
	modified:   driver-moab/main/prep_aoflux_mod.F90
	modified:   driver-moab/main/prep_atm_mod.F90
	new file:   driver-moab/main/prep_iac_mod.F90
	modified:   driver-moab/main/prep_ice_mod.F90
	modified:   driver-moab/main/prep_lnd_mod.F90
	modified:   driver-moab/main/prep_ocn_mod.F90
	modified:   driver-moab/main/prep_rof_mod.F90
	new file:   driver-moab/main/seq_diagBGC_mct.F90
	modified:   driver-moab/main/seq_diag_mct.F90
	modified:   driver-moab/main/seq_flux_mct.F90
	modified:   driver-moab/main/seq_frac_mct.F90
	modified:   driver-moab/main/seq_hist_mod.F90
	modified:   driver-moab/main/seq_io_mod.F90
	modified:   driver-moab/main/seq_map_mod.F90
	modified:   driver-moab/main/seq_map_type_mod.F90
	modified:   driver-moab/main/seq_rest_mod.F90
	modified:   driver-moab/shr/seq_comm_mct.F90
	modified:   driver-moab/shr/seq_drydep_mod.F90
	modified:   driver-moab/shr/seq_flds_mod.F90
	modified:   driver-moab/shr/seq_infodata_mod.F90
	new file:   driver-moab/shr/seq_pauseresume_mod.F90
	new file:   driver-moab/shr/shr_dust_mod.F90
	new file:   driver-moab/shr/shr_fan_mod.F90

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   cime_config/machines/cmake_macros/gnu_anlgce.cmake
	both modified:   cime_config/machines/cmake_macros/gnu_chrysalis.cmake
	both modified:   cime_config/machines/cmake_macros/intel_chrysalis.cmake
	both modified:   cime_config/machines/config_machines.xml
	both modified:   components/cmake/build_model.cmake
	both modified:   components/mpas-ocean/driver/mpaso_cpl_indices.F
	both modified:   components/mpas-seaice/driver/ice_comp_mct.F

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   components/cmake/modules/FindCsmShare.cmake
	modified:   share/CMakeLists.txt
```

2023-12-21 21:53 UTC, jgfouca commented
Congrats! This was a big change

2023-12-21 21:54 UTC, jgfouca commented
Do you want me to take a second look at any of those cmake conflicts?

2023-12-21 22:02 UTC, rljacob commented
Thanks!  You don't have to look at anything.  You had already shown how to fix it in  https://github.com/rljacob/E3SM/tree/jgfouca/moab_fixes.

What I didn't try was adding those changes to my branch so I wouldn't have to do it during the merge.  This branch only had some of your build changes so wasn't sure it would work.