Add ALCF Polaris to E3SM machines
E3SM-Project/E3SM pull request #6115
Opened 2023-12-09 04:05 UTC by amametjanov

Add ALCF Polaris to E3SM machines.

[BFB]

2023-12-09 06:02 UTC, rljacob commented on cime_config/machines/config_machines.xml
> +    <DIN_LOC_ROOT>/lus/swift/home/azamatm/polaris/inputdata</DIN_LOC_ROOT>
Is this a permanent location that doesn't depend on an INCITE or ALCC account?

2024-01-19 18:48 UTC, rljacob commented
@amametjanov is this ready?

2024-01-31 04:27 UTC, amametjanov commented
This should now be ready for review. I checked with
```
./cime/scripts/create_test --compiler gnugpu e3sm_gpucxx
./cime/scripts/create_test --compiler nvidiagpu e3sm_gpuacc
```

2024-01-31 21:39 UTC, rljacob commented on cime_config/machines/config_machines.xml
> +    <DIN_LOC_ROOT>/grand/SCREAM_Calib/inputdata</DIN_LOC_ROOT>
Please change this to /grand/E3SMinput   The permissions have been fixed.

2024-01-31 21:41 UTC, rljacob commented on cime_config/machines/config_machines.xml
> +    <CIME_OUTPUT_ROOT>/eagle/E3SM_RRM/$USER/scratch</CIME_OUTPUT_ROOT>
Doe ALCF have a $PROJECT variable we could put here instead of E3SM_RRM ?

2024-01-31 21:47 UTC, rljacob commented on cime_config/machines/config_machines.xml
> +    <CIME_OUTPUT_ROOT>/eagle/E3SM_RRM/$USER/scratch</CIME_OUTPUT_ROOT>
Or I guess we can use the PROJECT variable in the xml file.

2024-01-31 22:05 UTC, rljacob commented on cime_config/machines/config_machines.xml
> +    <DIN_LOC_ROOT_CLMFORC>/grand/SCREAM_Calib/inputdata/atm/datm7</DIN_LOC_ROOT_CLMFORC>
Fix this as well.

2024-01-31 22:06 UTC, rljacob commented on cime_config/machines/config_machines.xml
> +    <BASELINE_ROOT>/eagle/E3SM_RRM/baselines/$COMPILER</BASELINE_ROOT>
We need a better place for this too.

2024-01-31 22:07 UTC, rljacob requested changes
Need to change some paths.

2024-02-01 04:47 UTC, rljacob approved these changes

2024-02-13 02:56 UTC, merged