Fix bugs in OpenACC directives and revise machine files
E3SM-Project/E3SM pull request #6116
Opened 2023-12-10 21:02 UTC by hyungyukang

This PR fixes bugs in OpenACC directive in `mpas_ocn_diagnostics_variables.F` and `mpas_ocn_diagnostics.F`.

- Fix a bug in openacc directive in `mpas_ocn_diagnostics_variables.F` due to the AB2 option
- Change an openacc directive in `mpas_ocn_diagnostics.F` to avoid getting stuck before time integration on pm-gpu
- Change `Depends.pgigpu.cmake` to add the AB2 code for the openacc compilation
- Change nvidiagpu machine files to activate `MPAS_OPENACC` macro and a Fortran linker

@amametjanov , Thanks for reporting the problem. I fixed bugs and made some changes. Could you please test this branch?
I have tested this branch on PM-GPU using `SMS_Ld1.T62_oEC60to30v3.CMPASO-NYF` and `GMPAS-IAF` with `nvidiagpu` compiler, and now it's working properly.

2023-12-11 01:12 UTC, ndkeen commented
I'm seeing changes here that will have impact for other cases. We may need to find a way to make changes that will only affect MPAS

2023-12-11 14:06 UTC, hyungyukang commented
> I'm seeing changes here that will have impact for other cases. We may need to find a way to make changes that will only affect MPAS. If MPAS needs a flag, then maybe should only be applied to those sources. If you need `-acc`, maybe only use that flag for the sources required. And please don't change the GPU bindings unless we all agree upon those changes as they impact all cases.

@ndkeen , Thanks for your instructions. I'm going to revert some changes I made. It seems like the best way to add `-acc` to `nvidiagpu` in MPAS is to copy and modify `Depends.pgigpu.cmake`. What do you think about this?

2023-12-18 16:08 UTC, grnydawn requested changes
I also think that we may need to restrict the scope of impact from this changes within MPAS. Please see my comments in my review. I prefer to have a GPU bind suggested in this PR instead of "none". But it may need to coordinate with other developers who may impact to the GPU bind change.

2023-12-18 16:08 UTC, grnydawn commented on cime_config/machines/Depends.pm-gpu.nvidiagpu.cmake
> +# add accelerator/gpu flags for MPAS files
According to @ndkeen's comment, this setting might be placed in the Depends file, not in this cmake file, in order to limit the scope of impact to specified MPAS files.

2023-12-18 16:08 UTC, grnydawn commented on cime_config/machines/cmake_macros/nvidiagpu.cmake
> +string(APPEND CMAKE_Fortran_FLAGS " -i4 -Mstack_arrays -Mextend -byteswapio -Mflushz -Kieee -DHAVE_IEEE_ARITHMETIC -Mallocatable=03 -DNO_R16 -traceback -acc")
According to @ndkeen's comment, this setting might be placed in the Depends file, not in this cmake file, in order to limit the scope of impact to specified MPAS files.

2023-12-23 02:59 UTC, amametjanov commented
Rebased the branch onto latest master and checked that this PR still fixes the hang on PM-GPU: https://my.cdash.org/viewTest.php?buildid=2460796 .

2023-12-23 16:00 UTC, hyungyukang commented
@amametjanov , thanks for rebasing this PR!

@grnydawn , many changes I made in this PR were duplicates of #6103 (merged) except for `mpas_ocn_diagnostics.F`, so they disappeared by rebasing this PR.

@ndkeen , this PR fixes #6116.

2024-01-22 22:54 UTC, ndkeen approved these changes
Now need https://github.com/E3SM-Project/E3SM/pull/6166 to allow building, but after that, this fix allows the test to run

2024-01-25 19:24 UTC, grnydawn approved these changes
@amametjanov, the changes that Hyun made in "mpas_ocn_diagnostics.F." look good to me.

However, my test case (compset: GMPAS-IAF, res: T62_EC30to60E2r2) on Hyun's code branch (hkang/ocean/pm-gpu-fix) fails during building SPIO with the following error message:

```
"/global/u2/y/youngsun/repos/github/E3SM/externals/scorpio/src/clib/pioc.c", line 1282: error: too many arguments in invocation of macro "adios2_init"
          ios->adiosH = adios2_init(ios->adios_comm, adios2_debug_mode_on);
```

Since this error is not related to the changes in the MPAS code, I believe this PR is ready to be merged.

2024-01-26 02:53 UTC, merged