Fix C balance and FPE errors
E3SM-Project/E3SM pull request #6235
Opened 2024-02-13 18:33 UTC by peterdschwartz

Carbon balance was never checked correctly and let through negative values. 
Initialization of Ecosystem variables needed to be re-adjusted, and balance checking for FATES needed to be changed, which causes round-off differences in `CMASS_BALANCE_ERROR` for `fate_cold_allvars` test.

Also included divide-by-zero check in PhenologyMod.F90 to fix fpe in debug mode.

Fixes #6120 
Fixes #6203 
Fixes #6177

2024-02-13 18:42 UTC, peterdschwartz commented
@glemieux Here is a PR to fix the balance checking issues.  I did get DIFF for `fates_cold_allvars` but only for `CMASS_BALANCE_CHECK` but the values were still `~1E-16`.  

Let me know if how I implemented the new balance checking makes sense to you.

2024-02-15 23:17 UTC, glemieux approved these changes
The implementation looks good to me.  Thanks!

2024-02-21 15:02 UTC, peterdschwartz commented
After doing a test merge I obtained FILLDIFF for the `fates_cold_allvars`. That I need to look into today

2024-02-21 23:44 UTC, rljacob commented
What is the diff with?  A baseline from the previous code or is it a diff within a test like an ERS test?

2024-02-21 23:53 UTC, peterdschwartz commented
Not baseline diff (though that is also there but makes sense to me).  It fails the COMP_base_rest portion of ERP test (same thing with the ERS version I made for debugging).

2024-02-22 00:23 UTC, rljacob commented
Try a REP test.

2024-02-22 17:20 UTC, peterdschwartz commented
REP passes just fine. I'm going to double check that each variable for carbon balance is read/written to the restart file, and maybe a longer simulation will reveal diff's accruing in other fields.

2024-03-20 01:50 UTC, bishtgautam requested changes
I have minor stylistic code change requests for this PR.

2024-03-20 01:50 UTC, bishtgautam commented on components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90
> +      !nstep = nstep_mod
Please delete this line.

2024-03-20 01:50 UTC, bishtgautam commented on components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90
> +         beg_cropseedc_deficit     =>  grc_cs%beg_cropseedc_deficit  & ! Input: [real(r8) (:)] (gC/m2) column carbon pool for seeding new growth
Please remove an extra whitespace after `=>  grc_cs%` to be `=> grc_cs%`

2024-03-20 01:50 UTC, bishtgautam commented on components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90
> +      if(use_fates) then
please add a whitespace `if (use_fates)`

2024-03-20 01:50 UTC, bishtgautam commented on components/elm/src/biogeochem/EcosystemBalanceCheckMod.F90
> +         if(.not. use_fates) then
similarly add a whitespace.

2024-03-20 01:50 UTC, bishtgautam commented on components/elm/src/biogeochem/PhenologyMod.F90
> +         if( abs(ETo(p,kmo)) > 0._r8) then
- please add whitespace
- Shouldn't there also be code corresponding to an `else` condition?

2024-03-20 01:50 UTC, bishtgautam commented on components/elm/src/data_types/ColumnDataType.F90
> +       this%som_c_leached(i)             = value_column !! Grid Balance Error
Can you please remove the `!! Grid Balance Error`

2024-04-12 04:04 UTC, rljacob commented
@peterdschwartz what is the status of this PR?

2024-04-12 16:18 UTC, peterdschwartz commented
@rljacob I met with @glemieux  a couple of weeks ago. He mentioned a possible time-step dependent part of FATES that could be the cause, but I think he's been busy with the FATES api update and our follow up meeting with @thorntonpe was cancelled due to lab holiday.  

Today, I'll try increasing the history output to be every timestep and see if that provides any useful information.

2024-04-12 18:32 UTC, peterdschwartz commented
Update:

Increasing output freq finally showed a new diff in a field.  Looking into it further, it appears that the tendency term for carbon are not added to the leaching term due to some issue 5 years ago (according to git blame atleast), but it is for nitrogen and phosphorus. 

Hopefully the straightforward solution works here.
```
 LITR2C_TNDNCY_VERT_TRANS   (lndgrid,levdcmp,time)  t_index =    194   194
          3     5760  (   153,     2,     1) (   153,     1,     1) (   237,     3,     1) (   247,    10,     1)
                3165   1.043116371057806E-09  -1.643725044964128E-09 2.2E-19  2.944499461962624E-12 8.1E-11  1.293930177203629E-16
                3165   1.043116371057806E-09  -1.643725044964128E-09          2.944499678803059E-12          1.293930309552527E-16
                5760  (   153,     2,     1) (   153,     1,     1)
          avg abs field values:    4.034842251976478E-11    rms diff: 0.0E+00   avg rel diff(npos):  8.1E-11
                                   4.034842251976478E-11                        avg decimal digits(ndif):  7.1 worst:  7.0
 RMS LITR2C_TNDNCY_VERT_TRANS         0.0000E+00            NORMALIZED  0.0000E+00
```

2024-04-17 05:21 UTC, glemieux commented
@peterdschwartz can you point me to the line of code with the git blame that you noted earlier, please?

2024-04-17 15:58 UTC, peterdschwartz commented
@glemieux This [Code block](https://github.com/E3SM-Project/E3SM/blob/master/components/elm/src/data_types/ColumnDataType.F90#L7531) is what I was referring to. The transport tendency is not added to carbon leached pool even though the corresponding terms are added for Nitrogen and Phosphorus.  

More experimenting showed that bypassing the SoilLittVertTransp calculation, the restart failure goes away. For FATES, the `UpdateLitterFluxes`  is done just prior that adjusts the inputs to the `SoilLittVertTransp` that could be the cause.  [Line](https://github.com/E3SM-Project/E3SM/blob/master/components/elm/src/biogeochem/EcosystemDynMod.F90#L706)

2024-05-21 19:26 UTC, peterdschwartz commented
Since there's a previous fates related issue linked above with the same errors, I'm going to just clean the branch up for the other issues and follow the review comments. The other issue can be used to the issue.

2024-05-22 19:23 UTC, glemieux commented
> Since there's a previous fates related issue linked above with the same errors, I'm going to just clean the branch up for the other issues and follow the review comments. The other issue can be used to the issue.

Sorry for the delay in trying to address the fates-side of this.  Just to clarify, you're saying your going to move forwards towards integration @peterdschwartz?  If so, that sounds good to me.

2024-05-23 15:47 UTC, peterdschwartz commented
> > Since there's a previous fates related issue linked above with the same errors, I'm going to just clean the branch up for the other issues and follow the review comments. The other issue can be used to the issue.
> 
> Sorry for the delay in trying to address the fates-side of this. Just to clarify, you're saying your going to move forwards towards integration @peterdschwartz? If so, that sounds good to me.

@glemieux  Yes, and now I know how to how to reliably reproduce the issue, we can use #6125 to track progress. I will share a branch with the changes to do it.

@bishtgautam I have rebased the branch and addressed your comments.  There's potentially a couple of different ways to handle the `else` condition in the PhenologyMod, so I went with what I believe to be the simplest and added a comment explaining why.  Let me know what you think

e3sm_developer came back [BfB] with the exception of one FATES test that will FAIL restart comparison for the time being.

2024-05-23 18:44 UTC, bishtgautam commented on components/elm/src/biogeochem/PhenologyMod.F90
> +         end if
@peterdschwartz This looks good to me. Thanks for the comment explaining the logic.

2024-05-30 17:37 UTC, rljacob commented
This is ready to merge.

2024-05-30 17:37 UTC, bishtgautam approved these changes

2024-06-05 19:13 UTC, merged