adjusted use_extrasnowlayers parameters based on Schneider et al., 2021
E3SM-Project/E3SM pull request #6298
Opened 2024-03-18 19:42 UTC by chloewhicker

minor edits to tuning parameters in the use_extrasnowlayers scheme to follow recommendations from Schneider et al., 2021, change the snow refrozen grain radius (from 1000um to 1500um), and increase the max depth of snow (from 1m to 30m) for use_extrasnowlayers = true

2024-03-20 02:42 UTC, bishtgautam requested changes
The PR looks good. I only have requests for a few minor stylistic code mods.

2024-03-20 02:42 UTC, bishtgautam commented on components/elm/src/data_types/ColumnDataType.F90
> +    !end if
Please delete the commented out `if` and `endif` lines, and fix the indenting of the remaining lines.

2024-03-20 02:42 UTC, bishtgautam commented on components/elm/src/data_types/ColumnDataType.F90
> +                    if (use_extrasnowlayers) then
Please fix the indenting of this line.

2024-03-20 02:42 UTC, bishtgautam commented on components/elm/src/data_types/ColumnDataType.F90
> +                  end if
Please fix the indenting of this line.

2024-03-20 02:42 UTC, bishtgautam commented on components/elm/src/main/elm_instMod.F90
> +            !
Please fix the indenting of this line by removing a single whitespace in the beginning.

2024-03-25 18:46 UTC, bishtgautam approved these changes

2024-04-12 15:31 UTC, merged

2024-04-22 19:11 UTC, rljacob commented
This PR may have caused v3 restarts to no longer work with master.  That needs to be fixed.

2024-04-24 17:08 UTC, rljacob commented
Issue is https://github.com/E3SM-Project/E3SM/issues/6365