Land: temporarily disable long running developer tests
E3SM-Project/E3SM pull request #6305
Opened 2024-03-21 22:54 UTC by jgfouca

I suspect these will be re-enabled short, hopefully with adjustments to make them run faster on mappy. Both are taking 2 hours or more in their current state.

[BFB]

2024-03-22 04:25 UTC, rljacob commented
The elm-erosion test needs more examination.  @peterdschwartz noted: "when it was PASSing on mappy, the runtime is listed as 1hr".  @ndkeen said "ERS.hcru_hcru.I20TRGSWCNPRDCTCBC.pm-cpu_gnu.elm-erosion runs in 21.5 min on 1 node of pm-cpu"

2024-03-22 04:45 UTC, rljacob commented
We can look at master since its also tested on mappy.
Feb 27 pass: https://my.cdash.org/tests/127663013
hash cea78cb,  runtime: about 48 minutes.
March 1: fail  https://my.cdash.org/tests/129583246
hash 6c2f78d timed out 
mappy master had some issues between those dates so no runs.

Between those 2, these ELM-related PRs went in: #6233 #6266

2024-03-22 05:09 UTC, rljacob commented
It can be narrowed a bit using next:    fail 99a8988, pass 0d63448  PRs #6273, #6266.  There was a lot of activity on next and master around March 1st because we were finishing the v3.0.0 tag

2024-03-26 03:10 UTC, bishtgautam approved these changes

2024-03-26 03:23 UTC, tanzeli1982 approved these changes

2024-03-26 04:15 UTC, rljacob commented
@bishtgautam and @tanzeli1982 why are you approving removing the elm-erosion test when the problem seems to be unique to mappy?

2024-03-26 04:15 UTC, rljacob requested changes
Figure out why mappy and only mappy has a problem with the elm-erosion test.

2024-03-28 19:41 UTC, rljacob commented
@amametjanov did you have to add tasks for the elm-erosion test on chrysalis?

2024-03-28 20:29 UTC, amametjanov commented
Not on Chrysalis, but on Improv. I think the run-length could be reduced to either `_Ln9` or `_Ld3` (also adjust PEs from 48 to 64 on mappy).

2024-05-02 17:39 UTC, jgfouca commented
Discussed this PR during the IG meeting. Other folks are going to move these tests.

2024-05-02 17:39 UTC, closed without merging