output detailed aerosol radiation properties
E3SM-Project/E3SM pull request #6317
Opened 2024-04-02 00:44 UTC by mahf708

Adds additional detailed diagnostic outputs for aerosol radiation properties.

These diagnostics have long been used for production simulations (e.g., as inputs for SPA in SCREAM), but the code has never been incorporated in the main repository. The additions first include adding a visible-only `AER_TAU_SW_VIS` output to compare against AODVIS (if it weren't for not setting the night times to a `fillvalue`, the sum of this new output will be exactly the same as AODVIS). The more substantive addition are the optical properties needed for SPA `MODAL_AER_TAU_SW`, `MODAL_AER_SSA_SW`, `MODAL_AER_G_SW`, and `MODAL_AER_TAU_LW`. These outputs require adding two new history coordinates (`swband` and `lwband`), and can be ordered for RRTMG or RRTMGP (default to RRTMGP).

[BFB]

2024-04-03 17:10 UTC, singhbalwinder approved these changes
Looks good to me! I have left some very minor nit-picky comments.

2024-04-23 14:02 UTC, rljacob approved these changes

2024-05-30 17:38 UTC, rljacob commented
Any progress on restart issue?

2024-08-13 06:03 UTC, singhbalwinder requested changes
Thanks, Naser! Overall looks good to me but I have requested some minor changes.

You have added testmods but I don't see any new test added in this PR. Will there be a follow up PR with a test?

2024-08-13 14:21 UTC, singhbalwinder commented on components/eam/src/physics/cam/modal_aer_opt.F90
> +integer :: output_aer_props_rrtmgp = 1 ! 1=rrtmgp, 0=rrtmg
We should label it NBFB if it is going to cause DIFFs in the nightlies.

2024-08-13 14:23 UTC, singhbalwinder commented on components/eam/src/physics/cam/physpkg.F90
> +       call modal_aer_opt_coords
Yeah, that would be a better place to call it. If it doesn't work in the `*init` routine, you can call it from the `*register` routine.

2024-08-13 14:31 UTC, singhbalwinder commented on .github/workflows/e3sm-gh-ci-cime-tests.yml
> +          - ERS_P4.ne4pg2_oQU480.F2010.singularity2_gnu.eam-wcprod_F2010_spao
Sorry, I missed this file. This looks fine to me unless we would like to compare against the baselines. If we want to add it to the nightlies, we can add it to one of the integration suites.

2024-08-13 15:34 UTC, rljacob commented on .github/workflows/e3sm-gh-ci-cime-tests.yml
> +          - ERS_P4.ne4pg2_oQU480.F2010.singularity2_gnu.eam-wcprod_F2010_spao
Add it to e3sm_atm_integration

2024-08-13 15:40 UTC, rljacob commented on components/eam/src/physics/cam/modal_aer_opt.F90
> +   call addfld ('MODAL_AER_TAU_SW', (/'lev   ','swband'/), 'A', '1', &
Can you see if there's a CF standard name for any of these new variables and add it to the addfld call?
https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html

2024-08-13 15:49 UTC, rljacob commented on components/eam/src/physics/cam/modal_aer_opt.F90
> +   call addfld ('MODAL_AER_TAU_SW', (/'lev   ','swband'/), 'A', '1', &
I did some searching and looks like aerosol-radiative properties broken down by short/longwave are not there.

2024-08-13 16:49 UTC, rljacob commented on components/eam/src/physics/cam/modal_aer_opt.F90
> +   call addfld ('MODAL_AER_TAU_SW', (/'lev   ','swband'/), 'A', '1', &
Use the standard_name optional argument at the end of the call.
```
call addfld ('MODAL_AER_TAU_SW', (/'lev ','swband'/), 'A', '1', &
'Aerosol shortwave extinction optical depth', flag_xyfill=.true., &
standard_name='atmosphere_optical_thickness_due_to_ambient_aerosol_particles')
```

2024-08-14 19:14 UTC, closed without merging