add eamxx tests to e3sm suites
E3SM-Project/E3SM pull request #6640
Opened 2024-09-23 23:42 UTC by mahf708

Adds EAMxx tests to e3sm_atm_developer, e3sm_atm_integration, and  e3sm_atm_prod.

2024-09-24 00:18 UTC, rljacob commented on cime_config/tests.py
> +            "SMS_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.eamxx-prod"
We should test it as long as its used.

2024-09-24 15:32 UTC, jgfouca requested changes

2024-09-24 15:32 UTC, jgfouca commented on cime_config/tests.py
> +	        "SMS_D_Ln5.ne45pg2_ne45pg2.FAQP",
This line looks like it is not indented correctly.

2024-09-24 15:57 UTC, jgfouca approved these changes

2024-10-02 16:49 UTC, rljacob commented
@mahf708 is this ready?

2024-10-03 17:57 UTC, rljacob commented
Question:  should we add some/all of the tests that are currently in the various "e3sm_scream" suites to our nightly testing?

2024-10-03 19:12 UTC, rljacob commented
Adding more test can wait but I think you should create new suite names in preparation for that.   The "atm" suites are really EAM suites.   It shouldn't be necessary for an EAM developer to make EAMxx tests pass.  (Or should it?).   So maybe you should make new e3sm_eamxx_developer, e3sm_eamxx_integration, and e3sm_eamxx_prod suites, add the tests you've already added to those, and then include them in the corresponding e3sm full suites.

2024-10-03 19:55 UTC, rljacob commented
Good point.  If EAMxx depends on code in components/eam then we need an eamxx test.   That transition will take years but we need to build up our eamxx testing soon.   But new suites can also wait for another PR.

2024-10-08 00:44 UTC, rljacob approved these changes

2024-10-08 23:31 UTC, rljacob commented
maybe @oksanaguba can help with the HOMME errors on chrysalis.

2024-10-09 22:15 UTC, oksanaguba commented
i agree with Andrew that it would be better to wait till repos are merged together.

2024-10-10 01:39 UTC, rljacob commented
reverted from next.

2024-10-11 01:49 UTC, closed without merging