Add subgrid hillslope hydrology (NGEE Arctic IM2)
E3SM-Project/E3SM pull request #6718
Opened 2024-10-29 19:26 UTC by thorntonpe

This new capability builds on the existing topographic unit (topounit) subgrid scheme by implementing transport of water within a gridcell from higher to lower elevation topounits. Assuming that the topounit information on an existing surface dataset includes mean elevation for each topounit on a gridcell, the code will calculate topounit connectivity (topology) at run time during model initialization. On each time step a user-specified fraction of the surface runoff, ponded water runoff, and perched water table drainage terms are shifted to the next-lower topounit, where that water is distributed to the columns on the topounit with a user-defined decay term.
[BFB]
[FCC]
[NML]

2024-10-30 00:44 UTC, rljacob commented
Have there been any long-ish runs with this feature on?

2024-10-30 14:07 UTC, thorntonpe commented
@rljacob I can start a longer test - how long do you suggest?

2024-10-31 16:48 UTC, rljacob commented
I'd suggest a 1-year smoke test.  Is this going to be used by E3SM in some future version?

2024-10-31 16:57 UTC, thorntonpe commented
Thanks, I'll set that up. Next phase for this work is to evaluate multiple Arctic code changes operating together at the pan-Arctic scale (under ecosystem project NGEE Arctic). The plan would be to have this as a candidate capability in whatever version is current about three years from now.

2024-11-12 12:55 UTC, thorntonpe commented
@rljacob I ran a one-year test of this new capability on the global r05 land domain, based on the existing r05 topounit-enabled surface dataset. That run completed successfully. 
@tktesfa2014 and @bishtgautam I'm hoping you can provide your reviews. Let me know if you want to get together to discuss details.

2024-11-12 18:05 UTC, bishtgautam requested changes
@thorntonpe  I have left a few minor comments.

2024-11-12 18:05 UTC, bishtgautam commented on components/elm/src/biogeophys/SoilHydrologyMod.F90
> +      end do
Couldn't these weights be computed during initialization?

2024-12-19 18:15 UTC, rljacob commented
@thorntonpe ping.

2025-01-08 16:39 UTC, thorntonpe commented on components/elm/src/biogeophys/SoilHydrologyMod.F90
>        end do
Moved to a new loop, as suggested.

2025-01-08 16:39 UTC, thorntonpe commented on components/elm/src/data_types/ColumnDataType.F90
> +
Placed inside if statement, as suggested.

2025-01-08 16:40 UTC, thorntonpe commented on components/elm/src/data_types/TopounitDataType.F90
> +     call hist_addfld1d (fname='FROM_UPHILL',  units='mm',  &
Changed output field name and placed inside if statement, as suggested.

2025-01-08 16:40 UTC, thorntonpe commented on components/elm/src/main/organicFileMod.F90
> +
Removed lines.

2025-01-08 16:44 UTC, thorntonpe commented on components/elm/src/biogeophys/SoilHydrologyMod.F90
> +      end do
I'd rather leave the weight calculation in place during the time step since we are likely to have dynamic column weight on the topounit from other near-term developments.

2025-01-08 16:52 UTC, thorntonpe commented
@bishtgautam I made most requested changes in new commit and resolved all but one comment. The weight calculation could be done for now during initialization, but keeping it inline in the time step provides some future proofing for expected near-term development. Ready for your further review.

2025-01-09 00:43 UTC, bishtgautam reviewed
@thorntonpe, thanks for the changes. I left two more comments for you to consider.

2025-01-09 00:43 UTC, bishtgautam commented on components/elm/src/biogeophys/SoilHydrologyMod.F90
> +      end do
In that case, how about moving these computations within a `if (use_IM2_hillslope_hydrology)` block?

2025-01-09 00:43 UTC, bishtgautam commented on components/elm/src/main/elm_varcon.F90
> +  real(r8), public, parameter :: frac_from_uphill = 0.5  ! (fraction, valid values from 0.0 to 1.0)
How about adding `_r8`?

2025-01-09 14:38 UTC, thorntonpe commented on components/elm/src/biogeophys/SoilHydrologyMod.F90
> +      end do
Good idea - I moved this into a single if-block with the flux calculation.

2025-01-09 14:39 UTC, thorntonpe commented on components/elm/src/main/elm_varcon.F90
> +  real(r8), public, parameter :: frac_from_uphill = 0.5  ! (fraction, valid values from 0.0 to 1.0)
Done.

2025-01-09 14:39 UTC, thorntonpe commented
@bishtgautam thanks for the further review - requested changes are complete.

2025-01-09 15:48 UTC, bishtgautam approved these changes
The changes look good to me.

2025-01-13 16:52 UTC, thorntonpe commented
@tktesfa2014 would you be willing to take a look at this PR? It has already been reviewed by @bishtgautam but I'd like to get your input since it operates on top of the topounit structure. You can see the feature description document and other information at [https://acme-climate.atlassian.net/wiki/spaces/LAND/pages/4542398465/Subgrid+hillslope+hydrology+NGEE+Arctic+IM2](url)

2025-01-18 17:47 UTC, thorntonpe commented
@bishtgautam Not sure if I've done the right thing here. There were merge conflicts showing up in the PR github page. They were easy to resolve so I did that within github, and clicked the "merge commit" button shown in the conflict resolution page. Now the PR shows that master has been merged to my branch. Is that a problem for further integration?

2025-01-18 17:51 UTC, bishtgautam commented
@thorntonpe, the conflicts were indeed trivial, and I was planning on resolving them while merging your branch. We can force reset the branch to be at [874f2bc](https://github.com/E3SM-Project/E3SM/pull/6718/commits/874f2bc757d80ae94b91a4c99d51aa9ac19c9f22), thus removing the merge of master into your branch.

2025-01-20 00:23 UTC, rljacob commented
@thorntonpe don't do what github suggests for resolving merge conflicts.  It just merges master to the branch which we don't want.   @bishtgautam yes force reset the branch.

2025-01-22 00:10 UTC, rljacob commented
@tktesfa2014 please review

2025-01-22 22:20 UTC, tktesfa2014 commented on components/elm/src/main/initGridCellsMod.F90
@thorntonpe 
In current topounit-based surface data files, the topounit with lowest elevation has the smallest index number and the topounit with highest elevation has the highest index number. So, with the current data structure of the topounit-based surface data, the connectivity could be established easily. Can this also handle if we upgrade the topounit generation to include aspect?

2025-01-22 22:26 UTC, tktesfa2014 requested changes
@thorntonpe
I think you should use here a more recent topounit-based surface data file. For example:
topounit_based_half_degree_merge_surfdata_0.5x0.5_simyr1850_c211019.20211108_ed20220204.nc. This surface data file has gone through some improvement.

@thorntonpe
In current topounit-based surface data files, the topounit with lowest elevation has the smallest index number and the topounit with highest elevation has the highest index number. So, with the current data structure of the topounit-based surface data, the connectivity could be established easily. Can this also handle if we upgrade the topounit generation to include aspect?

2025-01-23 14:17 UTC, thorntonpe commented
> @thorntonpe I think you should use here a more recent topounit-based surface data file. For example: topounit_based_half_degree_merge_surfdata_0.5x0.5_simyr1850_c211019.20211108_ed20220204.nc. This surface data file has gone through some improvement.
> 
@tktesfa2014 I am looking for the suggested file in the inputdata directory (searching on perlmutter) but not finding it. I also see that the test for topounits, which is the root of this new test for IM2, uses the older file. I think it makes sense to use the same file for both tests. What do you think about leaving this as-is, and then we can make a new PR that updates the surface data file for both tests? In either case, can you point me to the new file?

> @thorntonpe In current topounit-based surface data files, the topounit with lowest elevation has the smallest index number and the topounit with highest elevation has the highest index number. So, with the current data structure of the topounit-based surface data, the connectivity could be established easily. Can this also handle if we upgrade the topounit generation to include aspect?

@tktesfa2014 having the topounits arranged this way on the surface data file makes sense. I think it is still safer to do the checks on topounit elevation within the code and assign the run-time indices accordingly. That avoids the need to make assumptions about the surface data file. The current organization will not break for a future definition of topounits that uses both elevation and aspect, but depending on how the aspect classes are defined the current implementation could be improved to optimize the hillslope connections. I think it is best to make those modifications if and when an aspect-based topounits definition is created.

2025-01-23 17:48 UTC, tktesfa2014 commented
@thorntonpe:
The updated topounit-based surface data is located at /compyfs/inputdata/lnd/clm2/surfdata_map/topounit_based_half_degree_merge_surfdata_0.5x0.5_simyr1850_c211019.20211108_ed20220204.nc. Could you point me to the input directory on Perlmutter so that I can upload it?

I think it makes more sense to use the one you have for this PR if you have used it in the test for IM2. I agree we can add the updated surface data in another PR. 

I have approved the PR. 
Thanks!

2025-01-23 17:49 UTC, tktesfa2014 approved these changes

2025-01-30 19:20 UTC, merged